### ISSUE TITLE
Problem compiling libigl tutorials

### ISSUE THREAD

**Issue by jannelliv** [eth-igl/GP2021-Assignments#10]
Hello,
I am trying to do subtask 2.2 in assignment 1. 
I have built the libigl tutorials, which are now in /libigl/tutorial. Specifically, I see the folders for tutorials 101-107, 201-206, 301-306, 401-407, 501, 507, 601-610, 701-715.
However, when I follow the instructions to compile the whole libigl library (which are: cd libigl; mkdir build; cd build; cmake ..; make -j2), and in particular when I execute "make -j2", I get the following exception at the end:

`[ 99%] Linking CXX executable ../../../igl_tests
[ 99%] Built target igl_tests
/mnt/c/Users/valer/Desktop/gp21-jannelliv/libigl/external/eigen/Eigen/src/Core/AssignEvaluator.h: In instantiation of ‘void Eigen::internal::call_assignment_no_alias(Dst&, const Src&, const Func&) [with Dst = Eigen::Matrix<bool, -1, -1>; Src = Eigen::CwiseBinaryOp<Eigen::internal::scalar_sum_op<bool, bool>, const Eigen::Matrix<bool, -1, -1>, const Eigen::Matrix<bool, -1, -1> >; Func = Eigen::internal::assign_op<bool, int>]’:
/mnt/c/Users/valer/Desktop/gp21-jannelliv/libigl/external/eigen/Eigen/src/Core/PlainObjectBase.h:732:41:   required from ‘Derived& Eigen::PlainObjectBase<Derived>::_set_noalias(const Eigen::DenseBase<OtherDerived>&) [with OtherDerived = Eigen::CwiseBinaryOp<Eigen::internal::scalar_sum_op<bool, bool>, const Eigen::Matrix<bool, -1, -1>, const Eigen::Matrix<bool, -1, -1> >; Derived = Eigen::Matrix<bool, -1, -1>]’
/mnt/c/Users/valer/Desktop/gp21-jannelliv/libigl/external/eigen/Eigen/src/Core/PlainObjectBase.h:816:7:   required from ‘void Eigen::PlainObjectBase<Derived>::_init1(const Eigen::DenseBase<ElseDerived>&) [with T = Eigen::CwiseBinaryOp<Eigen::internal::scalar_sum_op<bool, bool>, const Eigen::Matrix<bool, -1, -1>, const Eigen::Matrix<bool, -1, -1> >; OtherDerived = Eigen::CwiseBinaryOp<Eigen::internal::scalar_sum_op<bool, bool>, const Eigen::Matrix<bool, -1, -1>, const Eigen::Matrix<bool, -1, -1> >; Derived = Eigen::Matrix<bool, -1, -1>]’
/mnt/c/Users/valer/Desktop/gp21-jannelliv/libigl/external/eigen/Eigen/src/Core/Matrix.h:294:31:   required from ‘Eigen::Matrix<_Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols>::Matrix(const T&) [with T = Eigen::CwiseBinaryOp<Eigen::internal::scalar_sum_op<bool, bool>, const Eigen::Matrix<bool, -1, -1>, const Eigen::Matrix<bool, -1, -1> >; _Scalar = bool; int _Rows = -1; int _Cols = -1; int _Options = 0; int _MaxRows = -1; int _MaxCols = -1]’
/mnt/c/Users/valer/Desktop/gp21-jannelliv/libigl/external/pybind11/include/pybind11/operators.h:122:1:   required from ‘static B pybind11::detail::op_impl<(pybind11::detail::op_id)0, (pybind11::detail::op_type)0, B, L, R>::execute_cast(const L&, const R&) [with B = Eigen::Matrix<bool, -1, -1>; L = Eigen::Matrix<bool, -1, -1>; R = Eigen::Matrix<bool, -1, -1>]’
/mnt/c/Users/valer/Desktop/gp21-jannelliv/libigl/external/pybind11/include/pybind11/operators.h:71:28:   required from ‘void pybind11::detail::op_<id, ot, L, R>::execute_cast(Class&, const Extra& ...) const [with Class = pybind11::class_<Eigen::Matrix<bool, -1, -1> >; Extra = {}; pybind11::detail::op_id id = (pybind11::detail::op_id)0; pybind11::detail::op_type ot = (pybind11::detail::op_type)0; L = pybind11::detail::self_t; R = pybind11::detail::self_t]’
/mnt/c/Users/valer/Desktop/gp21-jannelliv/libigl/external/pybind11/include/pybind11/pybind11.h:1109:9:   required from ‘pybind11::class_<type_, options>& pybind11::class_<type_, options>::def_cast(const pybind11::detail::op_<id, ot, L, R>&, const Extra& ...) [with pybind11::detail::op_id id = (pybind11::detail::op_id)0; pybind11::detail::op_type ot = (pybind11::detail::op_type)0; L = pybind11::detail::self_t; R = pybind11::detail::self_t; Extra = {}; type_ = Eigen::Matrix<bool, -1, -1>; options = {}]’
/mnt/c/Users/valer/Desktop/gp21-jannelliv/libigl/python/modules/py_vector.cpp:213:10:   required from ‘pybind11::class_<Type> bind_eigen_2(pybind11::module&, const char*) [with Type = Eigen::Matrix<bool, -1, -1>]’
/mnt/c/Users/valer/Desktop/gp21-jannelliv/libigl/python/modules/py_vector.cpp:644:85:   required from here
/mnt/c/Users/valer/Desktop/gp21-jannelliv/libigl/external/eigen/Eigen/src/Core/AssignEvaluator.h:834:3: error: static assertion failed: YOU_MIXED_DIFFERENT_NUMERIC_TYPES__YOU_NEED_TO_USE_THE_CAST_METHOD_OF_MATRIXBASE_TO_CAST_NUMERIC_TYPES_EXPLICITLY
python/CMakeFiles/pyigl.dir/build.make:86: recipe for target 'python/CMakeFiles/pyigl.dir/modules/py_vector.cpp.o' failed
make[2]: *** [python/CMakeFiles/pyigl.dir/modules/py_vector.cpp.o] Error 1
CMakeFiles/Makefile2:5174: recipe for target 'python/CMakeFiles/pyigl.dir/all' failed
make[1]: *** [python/CMakeFiles/pyigl.dir/all] Error 2
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2`

I tried building in the python folder and it seems to go smoothly, but I still get this exception. Also, like I said, I do get the tutorial folders, so I don't know if this is an issue.

Thanks in advance for your help! :)

**Comment by FloorVerhoeven** [comment]
Hi @jannelliv 
If you manage to build the tutorials (as it seems you did) you don't need to build the whole libigl library separately. 
I'd suggest you remove the libigl/build folder to make sure no dangling bits will interfere later on but everything should work fine.
