### ISSUE TITLE
No .exe files after building the tutorials.

### ISSUE THREAD

**Issue by popavel** [eth-igl/GP2021-Assignments#11]
In Cmake I've chosen the libigl/tutorial as a source code folder and libigl/tutorial/build folder for the binaries.
After Configure and Generate I get generated .sln files for all the tutorials. 
However, when I open and build a solution with VS19 no executable is generated in the Release folder.

**Comment by FloorVerhoeven** [comment]
Hi @popavel 
We need more info to be able to help you. Did you get any error messages? Did any other files get created?

**Comment by popavel** [comment]
Hi @FloorVerhoeven 
Thanks for the fast reply. I was able to "fix" the issue. For some reason the executable (an it's related files) gets placed not in the Release folder (e.g. tutorial/build/101_FileIO/Release) but in the build folder itself (tutorial/build/). This makes the content of the build folder rather messy, but, apart from that, everything seems to work.

As a side note, I get the following message, when pressing Generate in CMake (not sure, if it's ok):

Could NOT find Vulkan (missing: VULKAN_LIBRARY VULKAN_INCLUDE_DIR) 
Using Win32 for window creation
Creating target: igl::opengl_glfw_imgui (igl_opengl_glfw_imgui)
CMake Deprecation Warning at CMakeLists.txt:4 (cmake_minimum_required):

  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.
