### ISSUE TITLE
Assignment 1: exercises 3 & 4

### ISSUE THREAD

**Issue by baclemen** [eth-igl/GP2021-Assignments#12]
so in exercises 3 & 4 is the idea to implement the functions yourself or just use the ones provided by libigl?

i'm mostly asking because in the comments it is written "your code", however when i just use one line which is a libigl function call, i don't really consider it my code.

**Comment by FloorVerhoeven** [comment]
Hi @baclemen 
For part 3 and 4 if there's a function included in the libigl version that comes shipped with this git repo, you're free to use it. Hence also the "Relevant libigl functions" hints. Assignment 1 is mostly about getting to know libigl, so some parts are indeed one-liners to code.
