### ISSUE TITLE
Assignment1: Shading

### ISSUE THREAD

**Issue by boduan1** [eth-igl/GP2021-Assignments#14]
1 Which mesh should I use for connected component part and subdivision part?
(for shading part I find the information to use 'fandisk.off' in Readme file but for connected component and subdivision I didn't find any information)
2 Do we need to choose a thershold such that all 3 image look different or is it fine that two looks the same?
3 Should this be corner shading?
![image](https://user-images.githubusercontent.com/58148182/110219593-8e3b3e80-7ec0-11eb-818f-323736c08159.png)

**Comment by FloorVerhoeven** [comment]
Hi @boduan1 
1) You can show screenshot for the Honda and coffeecup models for the connected components part, but please provide a table with for each mesh the number of components and the number of faces in each of the components. For the subdivision task please provide screenshots of the sphere and bumpy_cube meshes.
2) Please pick a threshold such that the per-corner shading looks different from the other two.
3) Yes, thank you for the mention

**Comment by boduan1** [comment]
Thanks!
