### ISSUE TITLE
Assignment1: facet_components

### ISSUE THREAD

**Issue by boduan1** [eth-igl/GP2021-Assignments#15]
I have an error with facet_components function, I think it can return a int type of the number of components, but I get an error,
what might be the problem?
![image](https://user-images.githubusercontent.com/58148182/110221094-69e45f80-7eca-11eb-8fe6-d59210cebac0.png)

**Comment by a-zeg** [comment]
I think this is a void function and that the output goes into the cid variable. Maybe just try
`igl::facet_components(F,cid);`

The variable cid should then contain for every face the id of the component to which this face belongs.

**Comment by boduan1** [comment]
In the code in facet_components, it gives the option of an int output?
![image](https://user-images.githubusercontent.com/58148182/110235644-941d3800-7f31-11eb-8bec-8d053845b74d.png)

**Comment by a-zeg** [comment]
Oh. In the libigl that I have locally (the one that came with the assignment), I only see two void constructors. Maybe I'm missing something or maybe we somehow have different versions. I guess I can't be of much help in either of those cases, sorry.

**Comment by boduan1** [comment]
Oh! that might be the problem, maybe the online version I checked doesn't match with the local version.
Thanks!

**Comment by FloorVerhoeven** [comment]
Hi @boduan1 
The libigl version we shipped with the assignment is not synced with the latest libigl version + documentation available online. We recommend checking your local header files for information about function usage.

**Comment by boduan1** [comment]
Thanks!
