### ISSUE TITLE
Assignment 1: Screenshots

### ISSUE THREAD

**Issue by nwicki** [eth-igl/GP2021-Assignments#18]
Hi everyone

Since it is rather tedious to take that many screenshots I was hoping we could automate the process. There is a file "render_to_png.h" which seems to be doing just that. However, I am having troubles linking the igl::png library in the cmake file.

Does anyone know how to do that? I thought I could just do the following:
Add this option:
option(LIBIGL_WITH_PNG ON)
Add igl::png to the linked libraries:
target_link_libraries(${PROJECT_NAME} igl::core igl::opengl_glfw igl::opengl_glfw_imgui igl::png)

The cmake process cannot find igl::png. What can I do to build the project properly?

Also, if there is a better way to create an image of the rendered mesh, please feel free to redirect me.

Thanks for any help.

**Comment by FloorVerhoeven** [comment]
Please have a look at #5 and #14

**Comment by wsh312** [comment]
It should be doable with OpenGL, but I don't think libigl has provided an API to do that. Maybe have a look at this example and implement it yourselve: https://github.com/libigl/libigl/issues/601
