### ISSUE TITLE
Assignment 1: Results required for 3.1 and 3.2,5 and 6

### ISSUE THREAD

**Issue by pitehu** [eth-igl/GP2021-Assignments#19]
I am wondering if we actually need to print out all these results? It would take quite a bit.

Also, could you tell me a good way to print vector of vectors? 

For 3.3, it seems super hard to check the answer from 3.1 and 3.2 visually as they are so many vertices and faces. What's a good way to do that? Also, do we need to run this on "plane.off" in addition to the default "bunny.off"?

For 5, it says "Show screenshots of the provided meshes with each connected component colored differently. Show the number of connected components and the size of each component (measured in number of faces) for all the provided models." Do we have to do this for all 9 models?

For 6, do we submit results for all the 9 models?

**Comment by wsh312** [comment]
Please refer to another issue: https://github.com/eth-igl/GP2021-Assignments/issues/5
