### ISSUE TITLE
Assignment 1: Viewer menu not showing

### ISSUE THREAD

**Issue by w-laura** [eth-igl/GP2021-Assignments#2]
In tutorial 106_ViewerMenu_bin the viewer menu is not showing up for me (see the screenshot below). Any idea what I am missing?

![Screenshot 2021-02-26 120044](https://user-images.githubusercontent.com/32953950/109292396-98a76980-782a-11eb-8650-5059a1f7a4d1.png)

**Comment by FloorVerhoeven** [comment]
Hi Laura,

This is apparently a known problem with libigl in combination with Visual Studio. The easiest workaround would be to compile in Debug mode temporarily. Please let me know if the problem persists when you do that. 
We'll look into a more permanent solution in the mean time.

**Comment by w-laura** [comment]
Alright thank you, it works in debug mode.

**Comment by wsh312** [comment]
Hi Laura,

Floor made a fix to your problem and I tried it on VS2019 and it should now work on the release mode as well. Please pull from the main repository and check.

**Comment by w-laura** [comment]
Perfect, I just pulled and it works in release mode now as well.
