### ISSUE TITLE
Assignment 1: Flipping Edge

### ISSUE THREAD

**Issue by pitehu** [eth-igl/GP2021-Assignments#21]
What exactly does "flipping edge" mean in the last step in the last question? For the example figure it seems that the inner edges are dropped while the outer edges are kept. Do I just implement as such?

**Comment by FloorVerhoeven** [comment]
@pitehu Yes, any original edges that have only 1 adjacent face you can just keep as is

**Comment by pitehu** [comment]
Does this other edges change at all?

**Comment by FloorVerhoeven** [comment]
@pitehu For the edges that get flipped (edges that connect 2 original points, of which at least 1 is not on the boundary of the mesh) you want to replace that edge with an edge that connects the 2 vertices that complete the 2 adjacent triangles. So if you have an edge connecting vertices i and j, plus the two adjacent triangles ijk and ijl, you want to connect vertex k with l.
