### ISSUE TITLE
Happy little accidents (a thread for funny buggy images)

### ISSUE THREAD

**Issue by ebonfalke** [eth-igl/GP2021-Assignments#23]
![Unbenannt](https://user-images.githubusercontent.com/21214417/110862406-bd3a2180-82bf-11eb-8eba-d90959af3b5e.PNG)
![Unbenannt2](https://user-images.githubusercontent.com/21214417/110862423-c1fed580-82bf-11eb-9a96-2bf43e0aa926.PNG)
![Unbenannt3](https://user-images.githubusercontent.com/21214417/110862432-c4612f80-82bf-11eb-99c9-ba82a6bd47c3.PNG)

What happens when one forgets to transpose a vector...

**Comment by wsh312** [comment]
Thanks for sharing!

**Comment by gilleswaeber** [comment]
![Capture d’écran de 2021-03-12 02-12-22](https://user-images.githubusercontent.com/13368639/110913684-bdfda280-8315-11eb-8b59-30626be174ba.png)

Here's the flying saucer! (expecting `resize` to be non-destructive)
