### ISSUE TITLE
General: failed to pull new assignment

### ISSUE THREAD

**Issue by azurite** [eth-igl/GP2021-Assignments#26]
When I run `git pull base master`to pull the new assignment it ends with a message `fatal: refusing to merge unrelated histories`. How can I successfully pull the new assignment?

If it helps my remotes are the following (I think this should be correct)
```
base    git@github.com:eth-igl/GP2021-Assignments.git (fetch)
base    git@github.com:eth-igl/GP2021-Assignments.git (push)
origin  git@github.com:eth-igl/gp21-azurite.git (fetch)
origin  git@github.com:eth-igl/gp21-azurite.git (push)
```

**Comment by azurite** [comment]
I so far managed to merge it with `git pull base master --allow-unrelated-histories` but then I had to manually resolve a lot of merge conflicts because I want to keep my solutions of assignment1 of course and I accepted some bug fixes inside `libigl` and typo fixes the main README.md file. Is this really the workflow for each new assignment or am I doing sh wrong here?

**Comment by wsh312** [comment]
Hi, what you did is correct. We will try to make fewer updates on the main REAEME.md and code to reduce the number of conflicts.
