### ISSUE TITLE
Logistics: Slide from Mar 12

### ISSUE THREAD

**Issue by pitehu** [eth-igl/GP2021-Assignments#28]
Is the slide from the exercise session on Mar 12 uploaded to the course website? I cannot seem to find it.

**Comment by wsh312** [comment]
Yes, I just check the website and believe it was uploaded: https://igl.ethz.ch/teaching/shape-modeling/sm2021/exercises/ex2_slides.pdf  maybe you need to use VPN outside the ETH network

**Comment by pitehu** [comment]
I don't think the link is anywhere on the course webpage https://igl.ethz.ch/teaching/shape-modeling/sm2021/ Also same for the slide used on Mar 19

**Comment by wsh312** [comment]
Hello,
You can find the link of last week here:
![image](https://user-images.githubusercontent.com/4659365/111996127-fe310200-8b19-11eb-9c22-82c08264df7c.png)
and this week that I just uploaded:
![image](https://user-images.githubusercontent.com/4659365/111996182-0ab55a80-8b1a-11eb-828d-51782491fa6b.png)
