### ISSUE TITLE
Assignment 2: Unexpected Constraint Points

### ISSUE THREAD

**Issue by pitehu** [eth-igl/GP2021-Assignments#29]
![image](https://user-images.githubusercontent.com/30425780/111694636-6ccc4200-8832-11eb-95ac-b93f03ea99bc.png)

I am trying to do task 1.1. It seems that for most points the results look okay but for some reason certain points aggregate on the y axis. Am I doing something wrong?

**Comment by wsh312** [comment]
Hi, that's wired, thoughts to debug:
(1) try different models to see the common of those bad points
(2) remove the 'good' points and only keep some 'bad' points (you can do the editing in Meshlab), then print out the computation process.

**Comment by pitehu** [comment]
I made some mistake in indexing and accessed some index that's out of bound.
