### ISSUE TITLE
General: More comments about using Python.

### ISSUE THREAD

**Issue by wsh312** [eth-igl/GP2021-Assignments#3]
You are welcome to use Python and the binding. However, for assignments 1-5, we will provide a c++ "skeleton code" for you to start with. We probably won't be able to provide the Python versions for you (I'm not a good Python coder myself). So you would need to do the transferring by yourselves. Ideally, all the Python users could help each other. Maybe those who want to use Python can post their name and email addresses below.

**Comment by Frankie8472** [comment]
Are you interessted in the creation of python templates for ex1-5? You could make it part of a bachelor or master thesis. The research aspect can be for example performance measurements or implementing/extending the igl library. I would have loved to do it but I got 4 other projects which are no less time consuming than smgp 😅
