### ISSUE TITLE
cannot build assignment 2 in windows 

### ISSUE THREAD

**Issue by duchaoyu** [eth-igl/GP2021-Assignments#30]
Dear tutors,
I cannot build assignment 2 properly in windows. I used cmake-gui, then run it in visual studio. Here is the error I get. 
![image](https://user-images.githubusercontent.com/43376817/111698237-e403d500-8836-11eb-872f-a4605a42fca2.png)
![image](https://user-images.githubusercontent.com/43376817/111698289-f1b95a80-8836-11eb-80ee-6981fb0497a3.png)

I'm so sorry that I'm not a c++ programmer so my question might be silly... I also struggled a lot in building assignment 1 ( but it somehow works... magically) I look forward to hearing from you and thank you for your answer in advance!

**Comment by wsh312** [comment]
Hi, thanks for your question. A few suggestions:
(1) Make sure to set the 'assignment 2' as the "start project" in VS2019.
(2) Directly download the code from the main repository to somewhere else and then directly compile assignment 2.
(3) Try both release and debug mode
(4) Check with the cmake options I used:
![QQ截图20210319083441](https://user-images.githubusercontent.com/4659365/111747923-2efe0680-8890-11eb-8433-1d0a9de4670b.png)
![QQ截图20210319084409](https://user-images.githubusercontent.com/4659365/111747936-332a2400-8890-11eb-92c4-07a43ddcec5a.png)

Don't hesitate if the problem still prexist

**Comment by duchaoyu** [comment]
Hi, thanks for your reply! I've done exactly what you have described.. but the same error still exists....

**Comment by wsh312** [comment]
It seems the errors link to ImGui. Are you able to build some of the tutorials, like 106?

**Comment by duchaoyu** [comment]
yes...

**Comment by wsh312** [comment]
![image](https://user-images.githubusercontent.com/4659365/111772312-020c1c80-88ad-11eb-8649-c16d31ccf35d.png)

maybe try to delete the "libigl/external" folder?

**Comment by duchaoyu** [comment]
What do you mean by deleting my "libigl/external" folder?

**Comment by wsh312** [comment]
I suspect you are missing some files in "GP2021-Assignments\libigl\external\imgui" (see the figures I attached) or some of those files are corrupted. So if you delete the entire "GP2021-Assignments\libigl\external" folder, the cmake will automatically download the external libraries.

**Comment by wsh312** [comment]
The key is to make sure your compiler (VS2019) can find the correct "include" files for imgui, using the correct path (see the previous image)

**Comment by wsh312** [comment]
Hi, here is Floor's comment: "the version of libigl/include/igl/opengl/glfw/imgui/ImGuiMenu.cpp is not up to date (i.e. doesn’t include the fix we pushed in commit 17756eb)"

One way to clean the libigl repo:

git pull base master
rm -r libigl
git submodule sync
git submodule update --init --recursive

**Comment by duchaoyu** [comment]
Thanks for the reply... None of these methods work so far. I guess I really screw things up. 
I just found out that the deadline of this exercise is 31st March. I think I will try to figure the problem out during the weekend. If it doesn't work, I would let you know. :) have a nice weekend!

**Comment by duchaoyu** [comment]
Hi, I solve it... I mess things up when I merge the branch and resolve conflicts...
