### ISSUE TITLE
Logistics: Typo in Assignment 2 slide deck

### ISSUE THREAD

**Issue by azurite** [eth-igl/GP2021-Assignments#31]
I believe there is a `yz` coefficient missing in the polynomial basis vector at the bottom of slide 11 of [ex2_slides.pdf](https://igl.ethz.ch/teaching/shape-modeling/sm2021/exercises/ex2_slides.pdf)

**Comment by wsh312** [comment]
Thank you for pointing it out! I will update the slides.
