### ISSUE TITLE
Assignment 2: chrono library

### ISSUE THREAD

**Issue by LeaRe** [eth-igl/GP2021-Assignments#33]
Are we allowed to use the `chrono` library for measuring the time?

**Comment by wsh312** [comment]
It sounds ok with me. But why not just use the time libraries in C++?

LeaRe ***@***.***> 于2021年3月24日周三 下午5:46写道：

**Comment by LeaRe** [comment]
I'm not very familiar with C++ so I just took the first time library I could find:) It works really well so I will just stick with chrono

**Comment by wsh312** [comment]
Ok, thanks for letting us know.

LeaRe ***@***.***> 于2021年3月25日周四 上午9:36写道：
