### ISSUE TITLE
Assignment 2: Constraint confusion

### ISSUE THREAD

**Issue by Frankie8472** [eth-igl/GP2021-Assignments#34]
Check that pi is the closest point to P_i+N; 
Check that pi is the closest point to P_i+2N; 
From which group of points? P or also the already new defined points in constrained_points?

If only P, then I don't get the second check, as P_i+2N is lying on the same sphere around P_i as P_i+N.

**Comment by wsh312** [comment]
P and the already new defined points in constrained_points.
Say from point P_i we generate new constraint points P_i+N and P_i+2N. If one uses a large \epsilon value, the closest point of P_i+N (or P_i+2N) could be P_j instead of P_i. Then one should decrease the size of \epsilon.  
![image](https://user-images.githubusercontent.com/4659365/112488869-389ad900-8d7e-11eb-8618-93ade7780389.png)

**Comment by Frankie8472** [comment]
Perfect, thx!
Then a follow up question. Who decides which point comes first? 
E.g. if P_j (created with eps) interferes with P_i (also created with eps) which eps do I halve?

**Comment by wsh312** [comment]
The idea is to use a small enough eps for all points, this should work with
simple shapes.

Franzelpanz ***@***.***> 于 2021年3月25日周四 下午3:28写道：

**Comment by Frankie8472** [comment]
great, thx!

**Comment by aserifi** [comment]
The first answer had me confused. 
When looking at this example:
![IMAGE 2021-03-27 12:13:05](https://user-images.githubusercontent.com/39410867/112718829-c9e08b80-8ef5-11eb-85bd-ab76b489a199.jpg)

do we also have to make sure that P_i+N is closer to P_i than P_j+N? or does it not matter and we only have to be closer than P_j?

**Comment by wsh312** [comment]
Yes and no. In the end, these generated constraints are approximations. Of
course, we want to make them as "accurate"  as possible, but for the
challenging case you draw it is hard to define a good sign distance value.
That's another reason why using the normal constrain is better than
position constrain. So please go ahead, we won't remove points if your
reconstruction results have artifacts in such regions.

Agon Serifi ***@***.***> 于 2021年3月27日周六 下午12:19写道：
