### ISSUE TITLE
Assignment 2: Grid outliers

### ISSUE THREAD

**Issue by acarigiet** [eth-igl/GP2021-Assignments#35]
I'm testing my implementation of task 2/3 on the bunny point cloud.  For degrees 0 and 1 the reconstruction works well, but for degree 2 there are outliers (gridpoints outside the bunny with the wrong sign) which cause artifacts to appear when MarchingCubes is applied.
Since there also seem to be a lot of outlying points on the grid in exercises session 2's example (Slide 25), I was wondering if this is actually expected.

![bunny_poly2_grid](https://user-images.githubusercontent.com/80133231/112532998-c5a75780-8da9-11eb-90dd-bd4fc839fa0a.PNG)
![bunny_poly2_re](https://user-images.githubusercontent.com/80133231/112533001-c63fee00-8da9-11eb-96fd-4784d5d1eb0c.PNG)

**Comment by wsh312** [comment]
Yes, this should be fine.

acarigiet ***@***.***> 于 2021年3月25日周四 下午8:39写道：

**Comment by acarigiet** [comment]
Thank you!
