### ISSUE TITLE
Assignment 2: deadline

### ISSUE THREAD

**Issue by azurite** [eth-igl/GP2021-Assignments#37]
On https://igl.ethz.ch/teaching/shape-modeling/sm2021/#ex2 it says that assignment 2 is due on 16.04.2021, 11:00 but in the readme at the root of this repo it says that the assignment 2 deadline is on 31.03.2021 11:00

I know from the email that the demo session has been moved but given the above information I'm not sure if the deadline for the assignment itself has moved as well or not.

Thanks for any clarifications.

**Comment by wsh312** [comment]
sorry, I forgot to update the git as well, thanks for pointing it out!
