### ISSUE TITLE
Assignment 2: MLS - Closed Form Solution

### ISSUE THREAD

**Issue by Frankie8472** [eth-igl/GP2021-Assignments#38]
I calculated the closed form solution by myself and got B^T * W * B * c = B^T * W * f. Did I make a mistake or is it safe to assume B^T has always an inverse? Because in the slides B^T is missing.

**Comment by wsh312** [comment]
Hi, I think the one shown in the slides is the definition of the linear equations, which could be solved by the normal equation method, as the solution you got. Please check http://www.nealen.net/projects/mls/asapmls.pdf for more detail.

**Comment by Frankie8472** [comment]
cool thx!
