### ISSUE TITLE
Build/Download of external libraries stopped working

### ISSUE THREAD

**Issue by Pideeeh** [eth-igl/GP2021-Assignments#39]
Since today I'm having trouble rebuilding the cmake projects for all Assignments.
Has there been a change from github not allowing fetches/pulls without usernames/passwords?
Because this works perfectly fine if I do the fetch manually with my github credentials

How could I fix this without greatly editing the according scripts?
Has this occured to anyone else?

`-- Creating target: igl::opengl_glfw_imgui (igl_opengl_glfw_imgui)
fatal: bad object bc6ac8b2aee0614debd940e45bc9cd0d9b355c86
fatal: HttpRequestException encountered.
   Fehler beim Senden der Anforderung.
bash: /dev/tty: No such device or address
error: failed to execute prompt script (exit code 1)
fatal: could not read Username for 'https://github.com': No error
CMake Error at C:/public/gp21-repo/libigl/external/.cache/imgui/imgui-download-prefix/tmp/imgui-download-gitupdate.cmake:55 (message):
  Failed to fetch repository 'https://github.com/ocornut/imgui.git'`
  
  Thanks

**Comment by FloorVerhoeven** [comment]
Hi @Pideeeh
That's the wrong repo tag for imgui. I suspect you have an old/corrupted version of the gp21-rep/libigl/cmake/LibiglDownloadExternal.cmake file

**Comment by Pideeeh** [comment]
Hi @FloorVerhoeven thanks for the reply.

Yes you are right. 
I managed to fix this by re-cloning my personal repo and pulling from your template repo with `--allow-unrelated-histories`

Sorry for reaching out too soon :)
