### ISSUE TITLE
Experimenting on WSL2 with vcXsrv

### ISSUE THREAD

**Issue by Frankie8472** [eth-igl/GP2021-Assignments#42]
When attempting to run the executable, has someone ever encountered the error 
> "The GLFW library is not initialized" 

or has some tips for solving/debugging this error?

_As for the X11 setup:_
> $xeyes -> works
> $glxheads  -> works

**Comment by wsh312** [comment]
hi, maybe download the clean code from the main repository and see if it works. If yes, then progressively add your own code and see which part causes the problem. If no, maybe something related to the library path definition.

**Comment by Frankie8472** [comment]
thx, will check that!
