### ISSUE TITLE
Assignment3: igl::gaussian_curvature vs igl::principal_curvature

### ISSUE THREAD

**Issue by azurite** [eth-igl/GP2021-Assignments#43]
We learnd that the gaussian curvature is the product of the two principal curvatures k1 and k2. The igl implementation of the gaussian curvature states in the header file `gaussian_curvature.h`

```
// Compute discrete local integral gaussian curvature (angle deficit, without
// averaging by local area).
```

So I ran the following small piece of code on the `torus.obj` file. It computes the gaussian curvature with averaging by the local area and compares it with the gaussian curvature obtained from `igl::principal_curvature`.

```cpp
Eigen::SparseMatrix<double> M, Minv;
igl::gaussian_curvature(V, F, K_Gaussian);
igl::massmatrix(V, F, igl::MASSMATRIX_TYPE_DEFAULT, M);
igl::invert_diag(M, Minv);
K_Gaussian = (Minv*K_Gaussian).eval();

Eigen::MatrixXd PD1, PD2;
Eigen::VectorXd PV1, PV2;
igl::principal_curvature(V, F, PD1, PD2, PV1, PV2);

cout << "error: " << (K_Gaussian - PV1.cwiseProduct(PV2)).norm() << endl;
```

The error is quite significant (error: 44.9984) so I was wondering why these two methods do not give the same result? I'm not sure what is meant with "angle deficit" in the documentation, maybe it has something to do with it.

**Comment by FloorVerhoeven** [comment]
Hi @azurite 
The gaussian_curvature() function uses the angle deficit definition for Gaussian curvature: per vertex it's simply 2pi minus the sum of the adjacent opening angles around the vertex. By definition this will always be within [0, 2pi], a scale independent, intrinsic quantity (it does not depend on the embedding of the surface in space). Computing the Gaussian curvature via the other route though does make it scale dependent (as you're multiplying principal curvatures whose magnitude depends on the size of the mesh). This is also not expected to stay in the range [0, 2pi]. A useful comparison would be to look at how they are similar/different **relatively** speaking. You could use Libigl's `jet()` function (without normalization) to compare how the values vary over the surface.

Also a small note: the averaging that is discussed in the `gaussian_curvature.h` file concerns an area-based averaging that is performed _during_ the curvature computation, not as a _post-processing_ step.

**Comment by azurite** [comment]
This makes a lot of sense thank you very much for the explanation!

I'm not sure if I misunderstood your second part though. I thought that `igl::gaussian_curvature` does not perform area-based averaging i.e. it computes (2π - ∑θj) for each vertex `v_i` without dividing by `A_i`, no?

**Comment by FloorVerhoeven** [comment]
You're right that it doesn't divide by `A_i`, what the comment in the code means however is that they also don't average by `A_j` when summing over the angles around vertex I.
