### ISSUE TITLE
Assignment 2: Additional Task (4)

### ISSUE THREAD

**Issue by MartinaKessler** [eth-igl/GP2021-Assignments#44]
For the additional task, where we need to use MeshLab to compute a mesh with poisson reconstruction and with RIMLS, do we have to explain in the report how those methods work, or is it enough to provide screenshots and compare the results with our MLS reconstruction?

**Comment by wsh312** [comment]
Hi, explaining the technical detail is not necessary, but please report your finding in the comparison results, e.g., which method performs better (in certain regions) and why is that the case?
