### ISSUE TITLE
Assignment 3: Task 1: Normals based on quadratic form

### ISSUE THREAD

**Issue by MartinaKessler** [eth-igl/GP2021-Assignments#45]
I have implemented the estimation of the normals based on the quadratic form. It looks almost good, except for some vertices:
![image](https://user-images.githubusercontent.com/79902237/113697624-bbebf100-96d3-11eb-897d-059cf3834c18.png)

I have already been debugging for some time, but I don't know where the bug could be hiding.
Do you have any idea where the error could be? Or do you have a hint how I could proceed with debugging?

**Comment by FloorVerhoeven** [comment]
Hi @MartinaKessler 

Some ideas: the direction could be inverted (do these points turn yellow when you click "invert normals" in the menu?), the normals could be 0-length or maybe contain NaN's. Try to identify these vertex indices by overlaying the vertex labels and print out the values for these normals.

**Comment by MartinaKessler** [comment]
Thanks for your feedback.
The normals turn yellow when I invert them. 
I printed the values of all the normals, where the dot product between the quadratic form normal and the normal calculated with igl::per_vertex_normals is smaller than 0.8. Those should be the normals that create those black dots.
I also compared the values of the normals with the other normals calculated in task 1,2 and 4, and they all agree on the value, except for the normals calculated with the quadratic form. They are not length 0 and they also don't contain NaN values. Here are the outputs for two points where the normal seems to be wrong:

> residual:  (A*x - b)
> -3.25251e-12
> -1.74802e-11
>     0.172089
> -2.04148e-11
>  2.13465e-11
>  -7.5413e-11
>  -7.5413e-11
> x:      -18.611      31484.6      -397360 -1.29826e+06       205864       336517
> Quadratic fitting normal:  0.997846 -0.046947 0.0458124
> igl normal:                      -1.61092e-17    -0.704383      0.70982
> Uniform normal:             -1.04357e-17    -0.712716     0.701452
> PCA normal:                     0 -0.706091  0.708121

> residual:  (A*x - b)
3.83915e-12
6.39688e-12
5.60219e-13
2.47846e-12
5.30997e-12
   0.244387
1.76237e-12
x:  3534.86  1377.27 -4430.71  20419.1 -12764.6  29462.4
Quadratic fitting normal:  0.912061  -0.12311 -0.391138
igl normal:                0.570022  0.818473 0.0719446
Uniform normal:            0.566478  0.820739 0.0740915
PCA normal:                0.568994  0.819213 0.0716646

For the second point, I really don't know why the normals is so wrong. For the first point I noticed that one of the coefficients of the quadratic polynomial is in the order of e+06, which causes this bad normal. But I don't know the solver outputs this huge value.

**Comment by FloorVerhoeven** [comment]
Try to debug this step by step. Check that the neighbourhood you use for the local PCA frame makes sense. For example use an overlay to highlight these points for the vertices that are giving you problems. Also print out the directions of the axis of the PCA frame to see that they make sense. Same goes for the height values that you are using.

**Comment by FloorVerhoeven** [comment]
Hi @MartinaKessler 
To come back to this: could it be that this goes away when you increase the value for k (the size of the neighbourhood
)? If that's the case then it might just be an instability (please write about this in the report if it's the case). You could check the dot product of each computed normal with for example normals computed with libigl's `per_vertex_normals()` function, and when this is negative flip the sign. That will give you a bit more uniform look without the black dots but likely you'll still see that these normals are a bit different than the surrounding ones. That can be fine, just explain in the report why it could be happening.

**Comment by LeaRe** [comment]
Hi @FloorVerhoeven , I have a very similar problem. Is it still possible to get full points for this task if we mention it in the report and try to find an explanation?

**Comment by FloorVerhoeven** [comment]
@LeaRe Yes, try to explain what may cause it and you should be able to get full points still. Some of these normal computations are more stable than others.
