### ISSUE TITLE
Assignment 3: curvature igl functions

### ISSUE THREAD

**Issue by MartinaKessler** [eth-igl/GP2021-Assignments#46]
In the assignment description it is written that there are relevant libigl functions: igl::gaussian curvature, igl::principal curvature, igl::cotmatrix, igl::massmatrix. I am not quite sure: Can we just use them for task where we need to calculate the curvature, or do we have to implement the curvature calculation ourselves?
Also, it is not explicitly written if we have to visualize the principal curvature directions. Could you clarify this please?

**Comment by FloorVerhoeven** [comment]
@MartinaKessler You're allowed to use these functions for assignment 3. No need to visualise the directions of the principal curvature, just their magnitudes as a colormap.
