### ISSUE TITLE
General: Which task gives how many points?

### ISSUE THREAD

**Issue by MartinaKessler** [eth-igl/GP2021-Assignments#47]
Dear TAs

It would help a lot to know in advance which task gives how many points, such that we can estimate how much of the assignment we have already solved and how important each task is relative to the other tasks in the assignment.
Would it be possible to give us this information for the next assignments. And if possible, it would also be great to know it for the current assignments 2 & 3.

**Comment by FloorVerhoeven** [comment]
Hi,

We only announce the points that can be earned per assignment as a whole (see slides for exercise session 1, although there could be small changes). The point distribution that explains your score for an assignment is sent out afterwards.
