### ISSUE TITLE
Assignment 3, Gaussian curvature

### ISSUE THREAD

**Issue by duchaoyu** [eth-igl/GP2021-Assignments#48]
Hi, I think I have done something wrong with my Gaussian curvature because my cow is always blue... However, I cannot find the problem. 😢  (my mean curvature works.. )
![image](https://user-images.githubusercontent.com/43376817/114310923-e0d5cf00-9aec-11eb-95f6-ec8c69351ba2.png)

```
Eigen::VectorXd K;
igl::gaussian_curvature(V, F, K);
Eigen::SparseMatrix<double> M, Minv;
igl::massmatrix(V, F, igl::MASSMATRIX_TYPE_VORONOI, M);
igl::invert_diag(M, Minv);
K_Gaussian = (Minv * K).eval();

igl::jet(K_Gaussian, true, colors_per_vertex);
viewer.data().set_colors(colors_per_vertex);
```

Hope to hear from you! Thank you very much in advance

**Comment by FloorVerhoeven** [comment]
I would suggest printing the values of `K_Gaussian` and `colors_per_vertex`. From what I can see this code looks good. Maybe one of these 2 variables is not of double or float type?

**Comment by duchaoyu** [comment]
Hi Floor! Thanks for the answer. Here's the output from Gaussian curvature igl::gaussian_curvature, Gaussian curvature multiplying the two main curvatures, and the mapping color using the latter method. 
I still cannot find out the error. I also don't understand why these two methods give me very different outcomes... 

```
Gaussian
    0.018679
  -0.0354353
   0.0127715
  -0.0395527
    0.019024
  -0.0111097
  0.00275546
  0.00112663
  0.00900552
  -0.0269753
 -0.00373862
   0.0111169
 -0.00929496
 -0.00170727
  -0.0161432
-0.000845821
   0.0234825
  -0.0372695
   -0.098072
  -0.0132216
Gaussian
-0.000523349
 0.000159678
 0.000889717
 -0.00137296
   0.0006652
-0.000501502
-0.000338966
  0.00154394
  0.00225865
 -0.00161205
  -0.0018751
  0.00132619
 -0.00392184
 -0.00084449
 -0.00721442
 -0.00258044
  0.00393932
  0.00472198
  0.00744521
  0.00330924
colors_per_vertex
       0 0.943178        1
       0 0.943614        1
       0  0.94408        1
       0 0.942635        1
       0 0.943937        1
       0 0.943192        1
       0 0.943295        1
       0 0.944498        1
       0 0.944954        1
       0 0.942482        1
       0 0.942314        1
       0 0.944359        1
       0 0.941007        1
       0 0.942973        1
       0 0.938905        1
       0 0.941864        1
       0 0.946027        1
       0 0.946527        1
       0 0.948266        1
       0 0.945625        1
```

```
    if (key == '7') {
        viewer.data().clear();
        viewer.data().set_mesh(V, F);

        colors_per_vertex.setZero(V.rows(),3);
        // Add your code for computing the discrete Gaussian curvature
        // store in K_Gaussian

        Eigen::VectorXd K;
        // Compute integral of Gaussian curvature
        igl::gaussian_curvature(V, F, K);
        // Compute mass matrix
        Eigen::SparseMatrix<double> M, Minv;
        igl::massmatrix(V, F, igl::MASSMATRIX_TYPE_VORONOI, M);
        igl::invert_diag(M, Minv);
        // Divide by area to get integral average
        //cout << K_Gaussian << endl;
        //cout << " " << endl;
        K_Gaussian = (Minv * K).eval();
        //cout << K_Gaussian << endl;

        cout << "Gaussian" << endl;
        cout << K_Gaussian.topRows(20) << endl;

        K_Gaussian.setZero();
        // Compute curvature directions via quadric fitting
        Eigen::MatrixXd PD1, PD2;
        Eigen::VectorXd PV1, PV2;
        igl::principal_curvature(V, F, PD1, PD2, PV1, PV2);
        // mean curvature
        for (int i = 0; i < V.rows(); i++) {
            K_Gaussian[i] = PV1[i] * PV2[i];
        }

        cout << "Gaussian" << endl;
        cout << K_Gaussian.topRows(20) << endl;

        // Compute pseudocolor
        igl::jet(K_Gaussian, true, colors_per_vertex);

        
        cout << "colors_per_vertex" << endl;
        cout << colors_per_vertex.topRows(20) << endl;

        // Set the viewer colors
        viewer.data().set_colors(colors_per_vertex);
```

**Comment by FloorVerhoeven** [comment]
I suspect it's a issue with normalisation in the `jet()` function. Right now it normalizes `K_Gaussian` to range from 0 to 1. If most of your values are around a small value (for example 0.001) but there is one very large value (say 2000) most of your data will be normalized to be near-zero (corresponding to blue color). So check the minimal and maximal values that occur in in `K_Gaussian` as well as the mean or median. Rather than using this version of `jet()` with `normalize=true` there is also a version which allows you to specify a min and max value that will correspond to blue and red yourself. This allows you to clip away any extreme values.

**Comment by duchaoyu** [comment]
Thank you Floor!

**Comment by duchaoyu** [comment]
most of my numbers are very small, except one extremely big number: `287.528`

**Comment by duchaoyu** [comment]
![image](https://user-images.githubusercontent.com/43376817/115578367-8515fd80-a2c5-11eb-8f1e-7635789f1c68.png)
I set the normalized to false... It seems there's something that happens along that boundary...?

**Comment by duchaoyu** [comment]
It is because the sum of angles (2π - ∑θj) along the boundary is way smaller than the others?

**Comment by FloorVerhoeven** [comment]
@duchaoyu 
Yes at boundaries the angle sum at boundaries will be smaller, and so the curvature defined by angle deficit will be larger. Have you tried something like `igl::jet(K_Gaussian, 0.0, 1.0, colors_per_vertex)`? This will clamp any values < 0 to the dark blue color, any > 1 to the red value and it will interpolate in between. You may need to adapt these values (0.0 and 1.0)

**Comment by duchaoyu** [comment]
yes. I was stuck on why this gigantic curvature happens. Now finally get it. Thank you very much, Floor😄 . Sorry for asking so many questions...
