### ISSUE TITLE
Assignment 3: Task 1 Normals based on quadratic fitting derivative

### ISSUE THREAD

**Issue by mkuerst** [eth-igl/GP2021-Assignments#49]
Hey

I don't quite understand how to obtain the normal from the derivative of the quadratic bi-variate polynomial. I calculated the coefficients of the quadratic bi-variate polynomial just like in igl::principal_curvature. If I'm not mistaken, the derivative of the polynomial corresponds to:

```
    IGL_INLINE double du(double u, double v)
    {
      return 2.0*a()*u + b()*v + d();
    }

    IGL_INLINE double dv(double u, double v)
    {
      return 2.0*c()*v + b()*u + e();
    }
```

In my understanding we need the two vectors that span the tangent plane that we just fitted with the quadratic bi_variate polynomial and take their cross product to get the normal. To get these vectors we need to calculate the derivative of the polynomial in u direction and the derivative of the polynomial in v direction right? If I understand correctly the derivatives are two scalars. I'm not sure how to get the two vectors to calculate the normal... 

Is the height function the polynomial we try to fit or am I wrong here aswell? (Sry I'm a bit confused :S)

**Comment by FloorVerhoeven** [comment]
Hi @mkuerst 

These functions do indeed describe the derivatives of the polynomial with respect to u and v (and it also immediately evaluates it (at given u,v values)) but it does not describe the derivatives of the **surface** that we're describing with this polynomial. I.e. we use it do define a surface r = (u, v, p(u,v)). For this surface we want to get the tangent vectors, so we need the derivative of r with respect to u and v. Maybe [this](https://math.etsu.edu/multicalc/prealpha/Chap3/Chap3-6/printversion.pdf) can help, have a look at the "Normal and Tangent Planes to Parametric Surfaces" section starting on page 4.

And yes indeed, the height values are what you use to fit the polynomial to.

**Comment by mkuerst** [comment]
Thank you for the answer :). So I tried to caluclate the normal with the tangent vectors (1, 0, p(u,v)/du) and (0,1, p(u,v)/dv). The results are wrong though. Do I need to take the derivatives of u and v w.r.t to x and y since they are projected to the height axis from the PCA normal?

If possible, (if that's not going too far in terms of assistance for the assignment) could you explain the intuition how the height samples are projected to the local frame of the PCA normal? Am I maybe even thinking too far?

**Comment by FloorVerhoeven** [comment]
Hi @mkuerst 
Be aware that the coordinates of the tangent vectors are with respect to the PCA frame so you'll need to at some point convert back to the "regular" xyz-coordinate frame. You could use [libigl's overlay edges](https://libigl.github.io/tutorial/#overlays) to plot the vectors you're working with by drawing an edge starting from the vertex and ending in vertex+direction.

When performing PCA, you don't just get the normal (which you used in the "PCA normal" part) but also 2 other vectors that lie in the best-fitting plane + you can get a point that lies on the plane (the original of your PCA frame). Given this origin, the normal vector and a vector from the PCA origin to a vertex you can compute how high the vertex is above/below the PCA plane (the height values).
