### ISSUE TITLE
Assignment 1: Clarifications about the report 

### ISSUE THREAD

**Issue by pchangmaths0327** [eth-igl/GP2021-Assignments#5]
Hello,

I have a small question about what is expected in the report, especially for the last two parts. For 3), the guideline says 

_"Show screenshots of the provided meshes with each connected component colored differently. Show the number of connected components and the size of each component (measured in number of faces) for all the provided models."_

What does _provided meshes_ mean? Do we have to take screenshots for the car and the coffeecup model only like in the handout, or for all 9 meshes in the data folder? I guess the second part about the number and size of components has to be done for all the meshes?

The same question arises for the subdivision scheme part: _Show screenshots of the subdivided meshes._ Is it only the sphere and the bumped cube like in the handout, or all of them?

Thank you for your time,

**Comment by wsh312** [comment]
> What does _provided meshes_ mean? Do we have to take screenshots for the car and the coffeecup model only like in the handout, or for all 9 meshes in the data folder? I guess the second part about the number and size of components has to be done for all the meshes?
> 

One can only take screenshots for the car and the coffeecup. But please report the components for all meshes we provided. You are welcome to show all screenshots.

> The same question arises for the subdivision scheme part: _Show screenshots of the subdivided meshes._ Is it only the sphere and the bumped cube like in the handout, or all of them?
> 
Similarly, the minimal requirement is to show the sphere and bumped cube only, but I suggest running on and showing on some complex ones (e.g., bunny, fandisk, and cup) to be sure.

**Comment by baclemen** [comment]
sorry but i'm not really satisfied with the answer "the minimal requirement is to ..." what does that mean? if we want to get all points is it enough to do "minimal requirements" or is that not enough?
