### ISSUE TITLE
General: Using optional dependencies

### ISSUE THREAD

**Issue by MikhailTerekhov** [eth-igl/GP2021-Assignments#50]
Hi,

Can we use the optional dependencies of libigl (in particular, I'm interested in CGAL) for our assignments?

**Comment by FloorVerhoeven** [comment]
Hi @MikhailTerekhov 

That would depend on which particular functions of CGAL you'd want to use I guess. Which ones were you thinking of?
Also beware that compiling with CGAL can be quite bothersome, we won't be able to help with compilation problems regarding CGAL.

**Comment by MikhailTerekhov** [comment]
It's 2D and 3D convex hulls for automatic non-axis-aligned bounding box selection. But maybe I'm overthinking this part :)

**Comment by FloorVerhoeven** [comment]
@MikhailTerekhov You can take the much simpler approach. Find the major axes of the point cloud (using PCA) and rotate the whole grid to match these axes. You can also determine the min. and max. values along these PCA axes.

**Comment by MikhailTerekhov** [comment]
@FloorVerhoeven ah, sure, I'll do that then, thank you!
