### ISSUE TITLE
Assignment 2: Inverted Normals

### ISSUE THREAD

**Issue by LeaRe** [eth-igl/GP2021-Assignments#51]
Is it okay if the normals of the reconstructed mesh are sometimes inverted? It's easy to correct it in the GUI with the "Invert Normals" button.

**Comment by FloorVerhoeven** [comment]
It's okay if it happens to some vertices, but shouldn't happen to all. If it happens to all, probably the handedness of the coordinate system you're using is wrong. If it happens to some, it should likely go away when using a higher value for k (for the PCA and quadratic fitting normals). If that's the case, please add a short explanation in the report why some normals are flipped for lower values of k.

**Comment by LeaRe** [comment]
This sounds a lot like task 1 from assignment 3, are we speaking of the same thing? For assignment 2, I don’t understand what k would be in my implementation

**Comment by FloorVerhoeven** [comment]
@LeaRe Apologies, I looked over that! I was indeed talking about Assignment 3. @wsh312 Could you answer for assignment 2?

**Comment by LeaRe** [comment]
@FloorVerhoeven Actually your answer helped me to solve my problem:) It was indeed a handedness problem when I compute the oriented bounding box with the help of PCA. I just needed to enforce righthandedness of the eigenvectors and now it's fine
