### ISSUE TITLE
Assignment Grading

### ISSUE THREAD

**Issue by pitehu** [eth-igl/GP2021-Assignments#52]
I don't think I can solve all the questions in assignment 2. How are the grades distributed in each question? Also, does assignment 1-6 account for the same proportion of the final grade?

**Comment by FloorVerhoeven** [comment]
Hi,
We only announce the points that can be earned per assignment as a whole (see slides for exercise session 1, although there could be small changes). The point distribution that explains your score for an assignment is sent out afterwards.

**Comment by Frankie8472** [comment]
Can you tell us what the required points are for a 4, 5, and 6?

**Comment by Frankie8472** [comment]
So this is a no?

**Comment by Frankie8472** [comment]
nvm, I overread: "The point distribution that explains your score for an assignment is sent out afterwards."

**Comment by FloorVerhoeven** [comment]
Hi @Frankie8472 
I seem to have missed your question. Because we have made some changes to the assignments this year we don't know the exact grading scale yet. I think you can expect around 60 points for a 4 and 100 points for a 6 but it there's some changes possible in that.

**Comment by Frankie8472** [comment]
great, thx!!!
