### ISSUE TITLE
Assignment 2: weighted least squares formulation

### ISSUE THREAD

**Issue by MikhailTerekhov** [eth-igl/GP2021-Assignments#53]
Hi,

In the presentation for the second assignment (slide 16), two formulations for weighted least squares are presented. I believe that the formulations are not equivalent. If we solve for
    c1 = argmin_c sum_i(wi * |b^T c - fi|^2), 
the normal equations will be 
    (B^T W B) c1 = B^T W F,
where B is the matrix of all basis functions of points in the neighborhood of x, W is the diagonal matrix with Wendland function values, and F is the column of known values for the points.

If we, on the other hand, solve the overdetermined system
    (W B) c2 = W F,
then the corresponding normal equations are
    (B^T W^2 B) c2 = B^T W^2 F

Of course, the difference is not that big: in the latter case we simply use the squared Wendland function weights, but it's still not the same. Which one was actually used in the master solution?

**Comment by wsh312** [comment]
Hi!

Thanks for your clarification! Since this was confusing, we will accept both "starting points" as long as the following deduction is correct. The paper "Interpolating and Approximating Implicit Surfaces from Polygon Soup" used the second definition.
