### ISSUE TITLE
Assignment 3: clarification kring vs knn with bfs

### ISSUE THREAD

**Issue by azurite** [eth-igl/GP2021-Assignments#54]
Recently there has been a change announced for assignment 3 regarding the k-nearest neighbors to clear up some misunderstanding. There are still some things that are not clear to me.

So far the first misunderstanding that has been cleared up is that we distinguish between **k-nearest neighbors** where "nearest" means the k points that are closest to some reference point with respect to euclidean distance. Then there is the **k-ring** of a point which defines the points that are at most k edges apart from some reference point in our graph. So f.ex the 1-ring is just the neighborhood of some vertex.

Now the part where I'm still confused is the part where we have to compute the pca normals. There the clarification said that we should use the **k-nearest neighbor** algorithm (not k-ring) but we should use the neighbors found by a bfs search. To quote from the email:

> For the “PCA computation” part we would explicitly like you to use the nearest neighbours found by a breadth-first search.

My first thought (before the email) was to just use `igl::knn()`. I'm not quite sure how we're supposed to implement a k-nearest neighbor algorithm ("nearest" based on euclidean distance) with bfs. Does this mean that we just run bfs from a vertex and use the first k vertices found as our "nearest neighbors" or do we still want the nearest neighbors with respect to euclidean distance? And if yes how does bfs help us accomplish this?

Also there would be the following problem. Imagine some part of a graph that is shaped like the following image
![photo_2021-04-14_19-21-14](https://user-images.githubusercontent.com/16439305/114752467-9a83a880-9d56-11eb-8590-b69c18406ac4.jpg)

Here nodes vi and vj are close in a euclidean sense but using a bfs to find vj from vi will take some time thus suggesting that they're not close together.

I'm sorry that the clarification email has confused me even more with this part. I hope someone can help me out with this. Maybe a toy example to illustrate how to use bfs to find the k-nearest neighbors or sh similar will help.

**Comment by FloorVerhoeven** [comment]
Hi @azurite 
Think about it as follows: we are trying to find normals to the surface, which we could do by taking the cross product of two tangent vectors at a point. When computing these tangent vectors we would base them on a local area around the point we're interested in. This property should carry over to the way we compute normals using PCA: we'd like the normal to a best-fitting plane to a local neighbourhood (close **on** the surface, geodesically). That's where bfs comes in, it _approximately_ finds the closest points in geodesic distance, i.e. the points that an ant living on the surface could get to quickest.
