### ISSUE TITLE
Assignment 3 normal orientation

### ISSUE THREAD

**Issue by boduan1** [eth-igl/GP2021-Assignments#56]
In PCA normal do we need to have orientation corrected?
My output seems have have some normal flipped.
![image](https://user-images.githubusercontent.com/58148182/115109729-d2b60180-9f77-11eb-8880-b67e5b0bb68c.png)
If needed should we build a graph and propagate in minimum spanning tree to have adjacent normal corrected?

**Comment by FloorVerhoeven** [comment]
Hi @boduan1 
You can fix flipped normals by checking their dot product with normals computed with the built-in libigl functions (e.g. `per_vertex_normals()`).

**Comment by boduan1** [comment]
> Hi @boduan1
> You can fix flipped normals by checking their dot product with normals computed with the built-in libigl functions (e.g. `per_vertex_normals()`).

Thanks!
