### ISSUE TITLE
Assignment 3 normal orientation

### ISSUE THREAD

**Issue by boduan1** [eth-igl/GP2021-Assignments#58]
Do we also need to correct the normal in Mean curvature normal by dot with reference? with the cotangent-weight formula it could also be flipped?
![image](https://user-images.githubusercontent.com/58148182/115125632-c22e7700-9fc9-11eb-88d7-6d4514b27c17.png)

**Comment by FloorVerhoeven** [comment]
Yes, the mean curvature normal is only determined up to sign so you need to orient it using some reference normals.

**Comment by boduan1** [comment]
Thanks!
