### ISSUE TITLE
General: Amending after final commit

### ISSUE THREAD

**Issue by azurite** [eth-igl/GP2021-Assignments#6]
In the workflow section in the README it says that we should submit our final solution for each assignment with a certain commit message

```
git commit -m "Solution assignment X"
git push
```

If we want to add some changes afterwards (but before the deadline) can we still do that as long as we always append a final commit with the above commit message?

So in the case where multiple commits contain said message above for the same assignment, will you look for the latest commit that contains the message "Solution assignment X"?

**Comment by wsh312** [comment]
Sure, please feel free to commit as much as you like before the deadline.
Please don't commit and push your code of the current assignment after the deadline and before we send you the scores, to make sure the latest timestamp is clear to us.
Please don't push your code too often to reduce the amount of email notification we receive ;)

**Comment by Frankie8472** [comment]
Sorry for all my commits, just read the post now...

Just an idea for next year, but what about just handing in the commit hash for the assignment solution in moodle or some kind of hand-in platform? Just thinking it seems kinda overkill if I use this gitrepo just for cloning and handins and another for tracking the progress (versioning). And the problem with email flooding and which commit to handin would be permanently solved.

**Comment by FloorVerhoeven** [comment]
Hi @Frankie8472 
No problem! I believe the notification issue has been resolved on our side, unfortunately there's just no mass unsubscribe button in GitHub Classroom. We'll look into how we can improve this for next year.
