### ISSUE TITLE
Assignment 3: Some Meshes not working

### ISSUE THREAD

**Issue by LeaRe** [eth-igl/GP2021-Assignments#60]
Hi, I can't run all the meshes in the data folder, some of them produce errors of this kind:

In the main function:
```
Warning: readOBJ() ignored non-comment line 1876:
  3 620 613 607
```
and then in the key 1 function:
```
squared_edge_lengths.h: Error: Simplex size (0) not supported
```
Will you run our code on all the meshes? Otherwise, I will just use those meshes that work to create the screenshots for my report. Those are the meshes that are not working for me:
cheburashka_noisy.off, cheburashka.off
eight_noisy.off, eight.off
fertility.off
lion.off
rocker-arm1250.off

I don't think the problem is in the code that I wrote because it already occurs in the main function. Is it okay if I leave it like that and just use the meshes that are working without affecting the grading?

**Comment by FloorVerhoeven** [comment]
Hi @LeaRe 
It seems like you're trying to use `readOBJ()` to open .off files. Does replacing `readOBJ()` with `read_triangle_mesh()`fix this issue?

**Comment by LeaRe** [comment]
Ah I see, I did not realize that we have different file types! Thank you, `read_triangle_mesh()` works for both .off and .obj :)
