### ISSUE TITLE
Assignment 3: igl::octree does not work on cow.obj

### ISSUE THREAD

**Issue by mikeqzy** [eth-igl/GP2021-Assignments#63]
Hi

I'm trying to use igl::octree and igl::knn to get k nearest neighbours for the PCA normal task. While it works for most meshes, I get a segmentation fault when I use igl::octree on cow.obj. Do you have any idea why it doesn't work? The code is:
`std::vector<std::vector<int>> O_PI;
        Eigen::MatrixXi O_CH;
        Eigen::MatrixXd O_CN;
        Eigen::VectorXd O_W;
        igl::octree(V, O_PI, O_CH, O_CN, O_W);`
Thank you.

**Comment by azurite** [comment]
I had the same issue in the beginning. Never found out why and with all other meshes it worked fine. However you're supposed to implement your own knn version based on bfs anyways. The TA's have sent a clarification mail a short while ago. Also #54 might help.

**Comment by MartinaKessler** [comment]
Do you mean that we need to implement breadth first search ourselves, or can we use igl::bfs for this task?

**Comment by mikeqzy** [comment]
@azurite 
Thank you for the reminder! I thought we can use igl::octree / igl::knn because of #40. Now that it does not work I may as well implement a bfs myself. However, after I checked #54 I am still confused about how bfs can help get knn points. I think it refers to the k-ring neighborhood. Can you give some hints on how to get knn points for PCA normal computation? Many thanks.

**Comment by duchaoyu** [comment]
@azurite Can I just use bfs to find the nearest neighbors? I'm now confused by reading all these.... Thanks for your answer.

**Comment by FloorVerhoeven** [comment]
@mikeqzy A segfault could come from a lot of different places, building in Debug mode should give you more information. 

For computing normals at a point we want to use data in a small neighbourhood, **on the mesh**, around that point. So not in Euclidean distance, but geodesic (distance if you could only move over the mesh). Doing this with a bfs gives an approximation to this neighbourhood (as we can only walk over edges in the discrete setting), which is fast to compute and good enough for computing normals.

**Comment by mikeqzy** [comment]
@FloorVerhoeven I see. So both PCA normal and quadratic fitting normal should use k-ring neighbourhood with a bfs. As far as I'm concerned nearest neighbour refers to the closest points in Euclidean distance, so the wording from the email is a bit confusing.
> For the “PCA computation” part we would explicitly like you to use the nearest neighbours found by a breadth-first search.
Thanks for the clarification!

**Comment by FloorVerhoeven** [comment]
@mikeqzy 
Thanks for the feedback! We'll take the confusion into account during the grading.
