### ISSUE TITLE
Assignment 3: 4. Smoothing with the Laplacian

### ISSUE THREAD

**Issue by nwicki** [eth-igl/GP2021-Assignments#65]
I am having troubles understanding how the smoothing process is implemented. As far as I can understand it from the slides, we need to update the vertices each iteration using an update step \lambda. For that we need to compute the Laplacian matrix, which is computed using cotmatrix and massmatrix functions.

In the implicit version implemented in tutorial 205, they also adjust the updated vertices with the average centroid and normalise it with the root of the whole area of the mesh, but I do not really understand why. Also, I don't see where we would use igl::grad as stated in the task description.

Can anyone point me in the right direction and also tell me if I understood anything wrongly?

**Comment by FloorVerhoeven** [comment]
Hi @nwicki 
For the explicit Laplacian smoothing please have a look at the blue box on slide 48 [here](https://igl.ethz.ch/teaching/shape-modeling/sm2021/course-notes/06_Smoothing_2021.pdf)

The centering and normalization applied in tutorial 205 is to prevent any numerical issues (as you smooth, the mesh will shrink and we want to avoid dealing with tiny triangles).

The suggestion to use `igl::grad` for constructing the Laplacian is just an alternative to using the cot matrix and massmatrix. See explanation [here](https://libigl.github.io/tutorial/#alternative-construction-of-laplacian)

**Comment by nwicki** [comment]
Thanks a lot for the pointers.

So, if I understood the slides correctly, there is no linear system to solve as opposed to the smoothing process using the implicit Euler since we only use derivatives of first order in the explicit Euler as opposed to the implicit Euler where we use second order derivatives right?

**Comment by Frankie8472** [comment]
As far as I understand: You have L_c and not L and the equation X_{t+1} = (I + t*L) * X_t. This leads with L = M^{-1} * L_c to M*X_{t+1} = (M + t*L_c) * X_t and therefore you have to solve a linear system? Please correct me if I'm wrong, my explicit smoothing is not smooth at all, rather spiky...
