### ISSUE TITLE
Assignment 4: most distant vertices

### ISSUE THREAD

**Issue by azurite** [eth-igl/GP2021-Assignments#67]
One version of the boundary condition consists of a free boundary but with two fixed vertices. The assignment suggests taking the two _most distant_ vertices as the fixed vertices.

Are we talking about geodesic distance or euclidean distance? Given the hint with dijkstra I think it is geodesic distance but I wanted to be sure before I continue.

**Comment by Guirec-Maloisel** [comment]
There is not a hard constraint on which distance to use, we leave it up to you to come up with a reasonable strategy or even to test out a few and keep the best.
Recall that there is in general not one optimal parameterization for a given mesh (except in very special cases were a global isometry is possible), so your results only need to be reasonable to be evaluated as correct.
