### ISSUE TITLE
Assignment 4: Boundary Conditions to Linear Constraints

### ISSUE THREAD

**Issue by Chiaki530** [eth-igl/GP2021-Assignments#68]
In function ConvertConstraintsToMatrixForm(), It is commented that the "The matrix C should contain only one non-zero element per row". To my understanding, matrix C should have size (2#V, 2#V). However, if the number of fixed boundary vertices is smaller than #V, should we leave empty rows for non-boundary vertices in C?

**Comment by Guirec-Maloisel** [comment]
The only constraint on the size of C comes from the fact that C * (u v)^T = d must be a valid matrix product. This fixes the number of columns, but the number of rows can be adapted to the number of constraints.
