### ISSUE TITLE
Error running the tutorial

### ISSUE THREAD

**Issue by ebonfalke** [eth-igl/GP2021-Assignments#7]
I get the following errors when running the first tutorial and don't know where I went wrong.

Fehler	LNK1181	Eingabedatei "..\..\Release\igl.lib" kann nicht geöffnet werden.	101_FileIO_bin	...\gp21-ebonfalke\libigl\build\tutorial\101_FileIO\LINK	1	
Fehler (aktiv)	E0020	Der Bezeichner ""M_PI"" ist nicht definiert.	igl	...\gp21-ebonfalke\libigl\include\igl\scaf.cpp	81	
Fehler	C2065	"M_PI": nichtdeklarierter Bezeichner	igl	...\gp21-ebonfalke\libigl\include\igl\scaf.cpp	81	
Fehler	C2065	"M_PI": nichtdeklarierter Bezeichner	igl	...\gp21-ebonfalke\libigl\include\igl\scaf.cpp	82

**Comment by FloorVerhoeven** [comment]
Hi @ebonfalke 

We need some more details to be able to help you. What did you do before you arrived at this point? 
Also what command do you execute when you say "when running the first tutorial"?

**Comment by ebonfalke** [comment]
Thanks for your reply. Sorry I was short on time yesterday.
I use Visual Studio on Windows 10. I followed the steps in the read.me. I used cmake + Visual Studio on the assignment1 and it compiles and runs without issues. I did the same for the tutorial folder but only the first got created so I did as mentioned in the exercise description and build the whole libigl instead and then tried to run the tutorials in the build folder which fails with the above error.

**Comment by wsh312** [comment]
Hi ebonfalke,

- Which VS version are you using, please try VS2019 community if you used an old version.
- You don't need to compile libigl before compiling the tutorial, so maybe try to undo the compiling of libigl.
- For CMake, please choose the x64 for generator, select the OPENGL related libraries:
![image](https://user-images.githubusercontent.com/4659365/109662954-e1815a00-7b6b-11eb-88e8-1866dd452797.png)

**Comment by ebonfalke** [comment]
Thanks the OPENGL options fixed the bug and now all tutorials get compiled aswell. 😃

Btw your assignment pdf states we should compile the whole libigl library if only one tutorial shows up which is why I did it in the first place:
"""Update: the above operation may only compile the first tutorial, if that’s the case, please compile the
whole libigl library, which will compile all the tutorials as well."""

**Comment by FloorVerhoeven** [comment]
@ebonfalke  Glad it works now!
For our administration: Did you issue `cmake -DLIBIGL_WITH_OPENGL=ON -DLIBIGL_WITH_OPENGL_GLFW=ON -DLIBIGL_WITH_OPENGL_GLFW_IMGUI=ON` **with** those 3 flags and it still only compiled the first tutorial?

**Comment by ebonfalke** [comment]
No with those 3 options it compiles all tutorials, but I had to set them manually.

**Comment by wsh312** [comment]
> Thanks the OPENGL options fixed the bug and now all tutorials get compiled aswell. 😃
> 
> Btw your assignment pdf states we should compile the whole libigl library if only one tutorial shows up which is why I did it in the first place:
> """Update: the above operation may only compile the first tutorial, if that’s the case, please compile the
> whole libigl library, which will compile all the tutorials as well."""

Thanks for pointing this out! I guess this suggestion is not applied to Windows, we will fix that.
