### ISSUE TITLE
Assignement 4: Distortion measurement

### ISSUE THREAD

**Issue by resema** [eth-igl/GP2021-Assignments#70]
Hi,

I'm trying to understand how we get in the lectures notes from the Jacobian `J_T` to the `E_LSCM(T)`.
![Screenshot 2021-05-04 at 08 58 49](https://user-images.githubusercontent.com/5762933/116969907-5af60f80-acb7-11eb-828a-76290c2ef7b5.png)

And secondly, I don't understand how this is linked to the distorsion measure equation in the exercise. How is `D(J)` linked to `E_LSCM(U)`?
![Screenshot 2021-05-04 at 09 02 24](https://user-images.githubusercontent.com/5762933/116970132-b1fbe480-acb7-11eb-812a-bf5590b00a66.png)

Thanks

**Comment by Guirec-Maloisel** [comment]
As written in the notes, E_LSCM measures the deviation from the patter (a b; -b a) of the Jacobian. Matrices with this pattern correspond to angle-preserving deformations (composition of rotation and uniform scaling), and vice-versa.

To check that a matrix has this pattern, we need to check that the diagonal coefficients are equal, and the extra-diagonal coefficients are opposite. This is why we take the sum of the extra-diagonal and the difference of the diagonal coefficients, which are supposed to be zero. Non-zero values indicate deviation from the template and are penalized by the energy.

Finally, you can check, by breaking down D(J) into what it does to the coefficients, that D and E_LSCM are exactly the same. D is just another formulation based only on matrix operations without relying on indexing. In your code and paper derivations, the more explicit formulation with coefficients might be easier to use.
