### ISSUE TITLE
Assignment 5: deformation transfer constraints

### ISSUE THREAD

**Issue by azurite** [eth-igl/GP2021-Assignments#72]
Currently when I'm transforming the mesh with deformation transfer the entire mesh translates in some (random?) direction after I move a handle to transfer the mesh. But otherwise the visual results of the distorted mesh after centering it from the user menu look ok to me. From my visualizations the meshes B and B' look correct (identical to detail transfer part).

When solving the deformation transfer system for the new vertex positions for the final deformed mesh S' do I have to manually include constraints that the handle vertex positions should stay the same during the deformation transfer or should this happen automatically and there is still something wrong with my implementation?

For small meshes I also printed the deformation gradients and for faces that are part of a handle this gradient is the identity matrix which looks correct to me.

Any help is appreciated.

**Comment by Guirec-Maloisel** [comment]
The system you solve as per the paper is only constraining the gradients of the mesh to match a target. When looking only at gradient information, you loose the "constant terms" i.e. the translation. So although it is not explicitly mentioned in the paper, you also have to solve this system under the positional constraints at the handles, using for instance the same substitution process as in the rest of the assignment.

**Comment by azurite** [comment]
The results look much better now when employing the substitution trick. Thanks! One thing I was wondering is whether the method with lagrange multipliers (as per the ex4 slides) works here as well? Because I tried this method first and after a while of dragging around handles the handle vertices would start to become very noisy and eventually they would still start to deform. Is this only a numerical issue or is there something else I'm missing?

**Comment by Guirec-Maloisel** [comment]
In theory Lagrange multipliers should work as well, but I am not an expert on that topic an on how it compares to other methods.

With what you describe however it sounds that some noise accumulates and is amplified with time. To get a stable solution, you should always solve the system to map the original mesh to the current handle positions (as opposed to from the previous solution). This way the solution you get depends only on the current handle positions and not on the path followed, so the error of consecutive system solves cannot accumulate.

**Comment by azurite** [comment]
Makes sense. Thanks for the explanation.
