### ISSUE TITLE
report

### ISSUE THREAD

**Issue by boduan1** [eth-igl/GP2021-Assignments#76]
Do we also need Screenshots of fixed boundary for LSCM and ARAP?

In the visualize do we need to set some threshold and color the higher one red, lower one white, or should we map the distortion value to color space and use a continuous coloring?

**Comment by Guirec-Maloisel** [comment]
Yes, for comparison we ask to see all methods with all applicable boundary conditions.

There is no hard constraint for the visualizations, but my advice would be to simply use a continuous coloring, as it is straightforward to implement. Setting thresholds is always a bit tedious otherwise.

**Comment by Guirec-Maloisel** [comment]
As a general advice, please try to start implementing the assignments earlier next time, as you can't expect us to be ready to answer all your last-minute questions immediately.

**Comment by boduan1** [comment]
OK and thanks for your advice!
