### ISSUE TITLE
Assignment 5 rotation

### ISSUE THREAD

**Issue by boduan1** [eth-igl/GP2021-Assignments#78]
I haven't write any code, and tried to select the handles, but there is an error when I try to do Rotate after selection.  

*** stack smashing detected ***: <unknown> terminated
Aborted (core dumped)

Is this a problem?

**Comment by HarriOrri** [comment]
Try building it in release mode, then you shouldn't have this problem

**Comment by boduan1** [comment]
> Try building it in release mode, then you shouldn't have this problem

Thanks! it works with release mode :)
