### ISSUE TITLE
Could not find git

### ISSUE THREAD

**Issue by MartinaKessler** [eth-igl/GP2021-Assignments#8]
When I use CMake gui to configure the project, I get the following error:

> Selecting Windows SDK version 10.0.17763.0 to target Windows 10.0.19041.
> CMake Error at C:/Program Files/CMake/share/cmake-3.15/Modules/ExternalProject.cmake:2410 (message):
>   error: could not find git for clone of eigen-download
> Call Stack (most recent call first):
>   C:/Program Files/CMake/share/cmake-3.15/Modules/ExternalProject.cmake:3204 (_ep_add_download_command)
>   CMakeLists.txt:9 (ExternalProject_Add)
> CMake Error at C:/Users/Martina/OneDrive/Dokumente/Studium/Informatik Master/FS2021/Shape Modeling and Geometric Processing/gp21-MartinaKessler/libigl/cmake/DownloadProject.cmake:171 (message):
>   CMake step for eigen failed: 1
> Call Stack (most recent call first):
>   C:/Users/Martina/OneDrive/Dokumente/Studium/Informatik Master/FS2021/Shape Modeling and Geometric Processing/gp21-MartinaKessler/libigl/cmake/LibiglDownloadExternal.cmake:14 (download_project)
>   C:/Users/Martina/OneDrive/Dokumente/Studium/Informatik Master/FS2021/Shape Modeling and Geometric Processing/gp21-MartinaKessler/libigl/cmake/LibiglDownloadExternal.cmake:52 (igl_download_project)
>   C:/Users/Martina/OneDrive/Dokumente/Studium/Informatik Master/FS2021/Shape Modeling and Geometric Processing/gp21-MartinaKessler/libigl/cmake/libigl.cmake:100 (igl_download_eigen)
>   cmake/FindLIBIGL.cmake:36 (include)
>   CMakeLists.txt:12 (find_package)
> Configuring incomplete, errors occurred!

I also cloned the libigl example project (https://github.com/libigl/libigl-example-project) and tried to generate it in CMake gui, but I got the same error.

I found this resource online: https://github.com/libigl/libigl/issues/1018, which states that "your cmake installation doesn't find an installation of git. Make sure git is installed and is in your PATH. The CMake documentation states that you need to have git version 1.6.5 or above installed for this." 
I checked my git version, it is 2.19.0. But I don't know how to check that git is in my PATH. Does anybody know how I can solve this issue?

**Comment by FloorVerhoeven** [comment]
Hi @MartinaKessler 

Please have a look here on how to add git to the PATH (in the process you'd also see if it's already there, but I suspect not) : https://www.answerlookup.com/how-add-git-windows-path-environment-variable

Make sure to change pathnames in step 6 to where git is located on your PC.

**Comment by MartinaKessler** [comment]
Hi @FloorVerhoeven 
Thanks a lot for your reply.
I followed the steps, but I realized that I don't have the folders named git\bin\ and git\cmd\
I installed git again (from this link: https://gitforwindows.org/), but still I don't have those folders. This is the content of my git folder:
![grafik](https://user-images.githubusercontent.com/79902237/109649771-a62b5f00-7b5c-11eb-8f14-5fac4706ecc8.png)
Do you have any ide what I could do to get those folders?

**Comment by wsh312** [comment]
Hi @MartinaKessler

In general, we are using an old version of libigl and you don't need to compile the libigl library.
I would suggest to try:
- Make sure you use a new version of CMake (e.g., 3.2) and use VS 2019.
- Clean up your repository or just copy the code from the main assignment repository
- Directly CMake assignment 1: 
![image](https://user-images.githubusercontent.com/4659365/109664388-5dc86d00-7b6d-11eb-8a75-efc47eec64a6.png)
![image](https://user-images.githubusercontent.com/4659365/109664435-69b42f00-7b6d-11eb-89c9-a498b42a72e0.png)
- Compile using "assignment1.sln"
- If it works, then compile the tutorials
 
![image](https://user-images.githubusercontent.com/4659365/109664891-ec3cee80-7b6d-11eb-925e-e93ad185fc3d.png)

**Comment by MartinaKessler** [comment]
Hi @wsh312 
Thanks for your help.
I deleted CMake, then reinstalled it to have the latest version. I also deleted the repository and cloned it again.
The visual studio version installed is indeed the 2019 version.
After having checked and done the things above the git error from before disappeared. But now I get a different error:
![grafik](https://user-images.githubusercontent.com/79902237/109692642-0f28cc00-7b89-11eb-80fb-22ddfcd98cc1.png)

Do you know what I could do to make it compile?

**Comment by FloorVerhoeven** [comment]
Hi @MartinaKessler 
Please try clearing the CMake cache (or even the whole build folder) and try again. If you get the same problem again could you please attach the CMakeOutput.log and CMakeError.log files in your next comment? The paths to them are in your screenshot.

**Comment by MartinaKessler** [comment]
I tried again and the error persisted. Here are the files:
CMakeOutput.log:

> The system is: Windows - 10.0.19041 - AMD64
> Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
> Compiler:  
> Build flags: 
> Id flags:  
> 
> The output was:
> 0
> Microsoft (R)-Build-Engine, Version 16.8.2+25e4d540b fr .NET Framework
> Copyright (C) Microsoft Corporation. Alle Rechte vorbehalten.
> 
> Der Buildvorgang wurde am 03.03.2021 09:06:54 gestartet.
> Projekt "C:\Users\Martina\OneDrive\Dokumente\Studium\Informatik Master\FS2021\Shape Modeling and Geometric Processing\gp21-MartinaKessler\assignment1\build\CMakeFiles\3.20.0-rc2\CompilerIdC\CompilerIdC.vcxproj" auf Knoten "1" (Standardziele).
> PrepareForBuild:
>   Das Verzeichnis "Debug\" wird erstellt.
>   Das Verzeichnis "Debug\CompilerIdC.tlog\" wird erstellt.
> InitializeBuildStatus:
>   "Debug\CompilerIdC.tlog\unsuccessfulbuild" wird erstellt, da "AlwaysCreate" angegeben wurde.
> ClCompile:
>   C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\bin\HostX64\x64\CL.exe /c /nologo /W0 /WX- /diagnostics:column /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\" /Fd"Debug\vc142.pdb" /Gd /TC /FC /errorReport:queue CMakeCCompilerId.c
>   CMakeCCompilerId.c
> Link:
>   C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\bin\HostX64\x64\link.exe /ERRORREPORT:QUEUE /OUT:".\CompilerIdC.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\CompilerIdC.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\CompilerIdC.lib" /MACHINE:X64 Debug\CMakeCCompilerId.obj
>   CompilerIdC.vcxproj -> C:\Users\Martina\OneDrive\Dokumente\Studium\Informatik Master\FS2021\Shape Modeling and Geometric Processing\gp21-MartinaKessler\assignment1\build\CMakeFiles\3.20.0-rc2\CompilerIdC\CompilerIdC.exe
> PostBuildEvent:
>   for %%i in (cl.exe) do @echo CMAKE_C_COMPILER=%%~$PATH:i
>   :VCEnd
>   CMAKE_C_COMPILER=C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\bin\Hostx64\x64\cl.exe
> FinalizeBuildStatus:
>   Die Datei "Debug\CompilerIdC.tlog\unsuccessfulbuild" wird gel”scht.
>   Aktualisieren des Timestamps von "Debug\CompilerIdC.tlog\CompilerIdC.lastbuildstate".
> Die Erstellung von Projekt "C:\Users\Martina\OneDrive\Dokumente\Studium\Informatik Master\FS2021\Shape Modeling and Geometric Processing\gp21-MartinaKessler\assignment1\build\CMakeFiles\3.20.0-rc2\CompilerIdC\CompilerIdC.vcxproj" ist abgeschlossen (Standardziele).
> 
> Der Buildvorgang wurde erfolgreich ausgefhrt.
>     0 Warnung(en)
>     0 Fehler
> 
> Verstrichene Zeit 00:00:01.62
> 
> 
> Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.exe"
> 
> Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.vcxproj"
> 
> The C compiler identification is MSVC, found in "C:/Users/Martina/OneDrive/Dokumente/Studium/Informatik Master/FS2021/Shape Modeling and Geometric Processing/gp21-MartinaKessler/assignment1/build/CMakeFiles/3.20.0-rc2/CompilerIdC/CompilerIdC.exe"
> 
> Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
> Compiler:  
> Build flags: 
> Id flags:  
> 
> The output was:
> 0
> Microsoft (R)-Build-Engine, Version 16.8.2+25e4d540b fr .NET Framework
> Copyright (C) Microsoft Corporation. Alle Rechte vorbehalten.
> 
> Der Buildvorgang wurde am 03.03.2021 09:06:56 gestartet.
> Projekt "C:\Users\Martina\OneDrive\Dokumente\Studium\Informatik Master\FS2021\Shape Modeling and Geometric Processing\gp21-MartinaKessler\assignment1\build\CMakeFiles\3.20.0-rc2\CompilerIdCXX\CompilerIdCXX.vcxproj" auf Knoten "1" (Standardziele).
> PrepareForBuild:
>   Das Verzeichnis "Debug\" wird erstellt.
>   Das Verzeichnis "Debug\CompilerIdCXX.tlog\" wird erstellt.
> InitializeBuildStatus:
>   "Debug\CompilerIdCXX.tlog\unsuccessfulbuild" wird erstellt, da "AlwaysCreate" angegeben wurde.
> ClCompile:
>   C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\bin\HostX64\x64\CL.exe /c /nologo /W0 /WX- /diagnostics:column /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\" /Fd"Debug\vc142.pdb" /Gd /TP /FC /errorReport:queue CMakeCXXCompilerId.cpp
>   CMakeCXXCompilerId.cpp
> Link:
>   C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\bin\HostX64\x64\link.exe /ERRORREPORT:QUEUE /OUT:".\CompilerIdCXX.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\CompilerIdCXX.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\CompilerIdCXX.lib" /MACHINE:X64 Debug\CMakeCXXCompilerId.obj
>   CompilerIdCXX.vcxproj -> C:\Users\Martina\OneDrive\Dokumente\Studium\Informatik Master\FS2021\Shape Modeling and Geometric Processing\gp21-MartinaKessler\assignment1\build\CMakeFiles\3.20.0-rc2\CompilerIdCXX\CompilerIdCXX.exe
> PostBuildEvent:
>   for %%i in (cl.exe) do @echo CMAKE_CXX_COMPILER=%%~$PATH:i
>   :VCEnd
>   CMAKE_CXX_COMPILER=C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\bin\Hostx64\x64\cl.exe
> FinalizeBuildStatus:
>   Die Datei "Debug\CompilerIdCXX.tlog\unsuccessfulbuild" wird gel”scht.
>   Aktualisieren des Timestamps von "Debug\CompilerIdCXX.tlog\CompilerIdCXX.lastbuildstate".
> Die Erstellung von Projekt "C:\Users\Martina\OneDrive\Dokumente\Studium\Informatik Master\FS2021\Shape Modeling and Geometric Processing\gp21-MartinaKessler\assignment1\build\CMakeFiles\3.20.0-rc2\CompilerIdCXX\CompilerIdCXX.vcxproj" ist abgeschlossen (Standardziele).
> 
> Der Buildvorgang wurde erfolgreich ausgefhrt.
>     0 Warnung(en)
>     0 Fehler
> 
> Verstrichene Zeit 00:00:01.36
> 
> 
> Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.exe"
> 
> Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.vcxproj"
> 
> The CXX compiler identification is MSVC, found in "C:/Users/Martina/OneDrive/Dokumente/Studium/Informatik Master/FS2021/Shape Modeling and Geometric Processing/gp21-MartinaKessler/assignment1/build/CMakeFiles/3.20.0-rc2/CompilerIdCXX/CompilerIdCXX.exe"
> 
> Detecting C compiler ABI info compiled with the following output:
> Change Dir: C:/Users/Martina/OneDrive/Dokumente/Studium/Informatik Master/FS2021/Shape Modeling and Geometric Processing/gp21-MartinaKessler/assignment1/build/CMakeFiles/CMakeTmp
> 
> Run Build Command(s):C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/MSBuild/Current/Bin/MSBuild.exe cmTC_8bda3.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=16.0 /v:m && Microsoft (R)-Build-Engine, Version 16.8.2+25e4d540b fr .NET Framework
> 
> Copyright (C) Microsoft Corporation. Alle Rechte vorbehalten.
> 
> 
> 
>   Microsoft (R) C/C++-Optimierungscompiler Version 19.28.29334 fr x64
> 
>   Copyright (C) Microsoft Corporation. Alle Rechte vorbehalten.
> 
>   CMakeCCompilerABI.c
> 
>   cl /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_8bda3.dir\Debug\\" /Fd"cmTC_8bda3.dir\Debug\vc142.pdb" /Gd /TC /errorReport:queue "C:\Program Files\CMake\share\cmake-3.20\Modules\CMakeCCompilerABI.c"
> 
>   cmTC_8bda3.vcxproj -> C:\Users\Martina\OneDrive\Dokumente\Studium\Informatik Master\FS2021\Shape Modeling and Geometric Processing\gp21-MartinaKessler\assignment1\build\CMakeFiles\CMakeTmp\Debug\cmTC_8bda3.exe
> 
> 
> 
> 
> Detecting CXX compiler ABI info compiled with the following output:
> Change Dir: C:/Users/Martina/OneDrive/Dokumente/Studium/Informatik Master/FS2021/Shape Modeling and Geometric Processing/gp21-MartinaKessler/assignment1/build/CMakeFiles/CMakeTmp
> 
> Run Build Command(s):C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/MSBuild/Current/Bin/MSBuild.exe cmTC_fb889.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=16.0 /v:m && Microsoft (R)-Build-Engine, Version 16.8.2+25e4d540b fr .NET Framework
> 
> Copyright (C) Microsoft Corporation. Alle Rechte vorbehalten.
> 
> 
> 
>   Microsoft (R) C/C++-Optimierungscompiler Version 19.28.29334 fr x64
> 
>   Copyright (C) Microsoft Corporation. Alle Rechte vorbehalten.
> 
>   CMakeCXXCompilerABI.cpp
> 
>   cl /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_fb889.dir\Debug\\" /Fd"cmTC_fb889.dir\Debug\vc142.pdb" /Gd /TP /errorReport:queue "C:\Program Files\CMake\share\cmake-3.20\Modules\CMakeCXXCompilerABI.cpp"
> 
>   cmTC_fb889.vcxproj -> C:\Users\Martina\OneDrive\Dokumente\Studium\Informatik Master\FS2021\Shape Modeling and Geometric Processing\gp21-MartinaKessler\assignment1\build\CMakeFiles\CMakeTmp\Debug\cmTC_fb889.exe

CMakeError.log:

> Determining if the include file pthread.h exists failed with the following output:
> Change Dir: C:/Users/Martina/OneDrive/Dokumente/Studium/Informatik Master/FS2021/Shape Modeling and Geometric Processing/gp21-MartinaKessler/assignment1/build/CMakeFiles/CMakeTmp
> 
> Run Build Command(s):C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/MSBuild/Current/Bin/MSBuild.exe cmTC_dc180.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=16.0 /v:m && Microsoft (R)-Build-Engine, Version 16.8.2+25e4d540b fr .NET Framework
> 
> Copyright (C) Microsoft Corporation. Alle Rechte vorbehalten.
> 
> 
> 
>   Microsoft (R) C/C++-Optimierungscompiler Version 19.28.29334 fr x64
> 
>   Copyright (C) Microsoft Corporation. Alle Rechte vorbehalten.
> 
>   CheckIncludeFile.c
> 
>   cl /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_dc180.dir\Debug\\" /Fd"cmTC_dc180.dir\Debug\vc142.pdb" /Gd /TC /errorReport:queue "C:\Users\Martina\OneDrive\Dokumente\Studium\Informatik Master\FS2021\Shape Modeling and Geometric Processing\gp21-MartinaKessler\assignment1\build\CMakeFiles\CMakeTmp\CheckIncludeFile.c"
> 
> C:\Users\Martina\OneDrive\Dokumente\Studium\Informatik Master\FS2021\Shape Modeling and Geometric Processing\gp21-MartinaKessler\assignment1\build\CMakeFiles\CMakeTmp\CheckIncludeFile.c(1,10): fatal error C1083: Datei (Include) kann nicht ge”ffnet werden: "pthread.h": No such file or directory [C:\Users\Martina\OneDrive\Dokumente\Studium\Informatik Master\FS2021\Shape Modeling and Geometric Processing\gp21-MartinaKessler\assignment1\build\CMakeFiles\CMakeTmp\cmTC_dc180.vcxproj]
>

**Comment by FloorVerhoeven** [comment]
@MartinaKessler Did you successfully manage to compile the libigl tutorials before hand?

**Comment by wsh312** [comment]
@MartinaKessler is it possible to try it on another computer (ideally with English as the system languagege) to rule out the possibility of corruption of system variables?

**Comment by MartinaKessler** [comment]
I managed to compile and run the tutorials from the libigl example project (https://github.com/libigl/libigl-example-project), but the tutorials contained in the libigl/tutorial folder from my git repository don't compile. So I assume that there must be something wrong with my git repository. The only thing that I noted that was strange was that when I executed the command

> git pull base master

I received the error 

> refusing to merge unrelated histories

I solved the error by changing the command to

> git pull base master --allow-unrelated-histories

Could this be the problem?
How could I reset my git repository such that I can try again?

I could try it out on a different computer, but I would have to install Visual studio, a c++ compiler, CMake and Git. So if possible I would like to try it with my laptop where everything is already installed.

**Comment by wsh312** [comment]
Compiling the tutorial is not necessary, but make sure you can add the UI stuff in your assignment 1 code.
Sometimes there are wired git issues that hard to resolve, you can update your git repository manually.
You could also try to register a new Github account and start from scratch.

**Comment by FloorVerhoeven** [comment]
If you don't want to setup a different GitHub account, you can also delete the current repository and make a new one. Go to https://github.com/eth-igl/gp21-MartinaKessler, then go to settings and at the bottom of the page there should be the delete option. You can then setup a new repo with the instructions from https://github.com/eth-igl/GP2021-Assignments again. 
Make sure that if you have to use the `--allow-unrelated-histories` command, that you successfully merge afterwards (check with `git status`).

**Comment by MartinaKessler** [comment]
I just deleted my git repository, then created a new one and did the whole compiling process again, but I got the same errors as before. Neither the tutorial nor the assignment1 compile.

**Comment by MartinaKessler** [comment]
I managed to get it working by having a folder containing the libigl example project (https://github.com/libigl/libigl-example-project) and the assignment1
![grafik](https://user-images.githubusercontent.com/79902237/110094669-5b982580-7d9c-11eb-9339-ccc99605bf50.png)
This compiles and runs.
But now my project does not have exactly the same structure as the git repository I cloned which does not compile. I compared the libigl folder from the example project and the libigl folder in my git repository and they don't have exactly the same content, e.g. there are 882 elements in the libigl/include/igl folder of the example project, but only 765 elements in the libigl/include/igl folder of the git repository.
I could create a new git repository, but then I don't have exactly the structure that I assume you expect for the hand-in of the assignments. What do you propose I should do?

**Comment by wsh312** [comment]
Hi, we don't require any structure of your git repository.
We simply go to "your git repository"/assignmentX and check your code and report there.

**Comment by wsh312** [comment]
Hi Martina,
I saw one issue similar to yours: https://github.com/NYUGraphics/GM_Assignment_2/issues/4
Could you try that solution, i.e., removing the external/?

**Comment by MartinaKessler** [comment]
I removed the content in the libigl/external folder, but this resulted in the same error as before.
As discussed with @FloorVerhoeven the whole project compiles if the ImGui components are removed

```
cmake_minimum_required(VERSION 3.1)
project(assignment1)

set(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} ${CMAKE_CURRENT_SOURCE_DIR}/cmake)

# libigl
option(LIBIGL_WITH_OPENGL            "Use OpenGL"         ON)
option(LIBIGL_WITH_OPENGL_GLFW       "Use GLFW"           ON)
#option(LIBIGL_WITH_OPENGL_GLFW_IMGUI       "Use ImGui"           ON)

find_package(LIBIGL REQUIRED QUIET)

# Add your project files
FILE(GLOB SRCFILES src/*.cpp)
add_executable(${PROJECT_NAME} ${SRCFILES})
#target_link_libraries(${PROJECT_NAME} igl::core igl::opengl_glfw igl::opengl_glfw_imgui)
target_link_libraries(${PROJECT_NAME} igl::core igl::opengl_glfw)
```

**Comment by FloorVerhoeven** [comment]
Update: In this case it turned out the path name to the libigl folder was too long, shortening it resolved the issue. For debugging this yourself, go to line 18 of libigl/cmake/LibiglDownloadExternal.cmake and comment out the "QUIET" command to get more debugging info.
