### ISSUE TITLE
Assignment 5 Show B

### ISSUE THREAD

**Issue by boduan1** [eth-igl/GP2021-Assignments#80]
How can we switch show B mesh?
I tried to add in solve function

viewer.data().clear();
viewer.data().set_mesh(VB, F);

but it still show V

**Comment by resema** [comment]
I solved this by just storing all intermediate meshes and assigning them to V as desired. This way I can restart from each step.

**Comment by boduan1** [comment]
But if we set V to VB, then from the later steps we deform from VB?

**Comment by resema** [comment]
I'm not sure if I understand you correctly. But I'm storing all intermediate steps, and can start for later steps from each intermediate. I have 4 buttons to show each one, and if I want to continue normally after showing an intermediate I just push the final mesh button.

**Comment by boduan1** [comment]
Thanks!
