### ISSUE TITLE
Assignment 5 rendering speed

### ISSUE THREAD

**Issue by gilleswaeber** [eth-igl/GP2021-Assignments#82]
I encounter an issue with the bumpy plane mesh. The computations completes in ~30-50ms on my laptop but the renderer takes sometimes seconds to update when I keep on moving. After logging the times, it seems that the solving is nearly executed in a tight loop and it doesn't let the view update.

Is there some requestAnimationFrame function or some way to debounce the mouse move callback?

**Comment by FloorVerhoeven** [comment]
Hi @gilleswaeber 
Not sure I completely understood what your issue is but it sounds like you're not achieving interactive rates? Did you read and implement part 1.5 already? If not, that might a possible issue. Also make sure you're in Release mode, and not Debug mode.
If you're still debugging your code you might want to define the `UPDATE_ONLY_ON_UP` macro which will call the `solve()` function only when the mouse button is released (but for the demo we want to see interactive updates).

**Comment by resema** [comment]
I think I observe the same issue. I implemented part 1.5 and the calculation time for the method `solve` is done in ~30ms for the bumpy plane, but the scene update in the GUI is taking up to 1-2 seconds. Is there a way to trigger the scene update to improve to real time translation/rotation?

**Comment by gilleswaeber** [comment]
The view is just frozen. I can see that the solve is running a lot of time because it shows up in the log, but the window does not change. I even get the window not responding message in some cases. 

The code is compiled in release mode on Linux (fedora) with clang.

**Comment by boduan1** [comment]
Do we need every mesh to have >10 fps? My bumpy_plane is only 3 fps

**Comment by FloorVerhoeven** [comment]
@resema @gilleswaeber You can see if adding the lines `  viewer.core.is_animating = true;
  viewer.core.animation_max_fps = 30;` helps. If it doesn't, please push your code and I might be able to have a quick look at it to see if there's anything obvious. 

@boduan1 3 fps is fine for the bumpy_plane, the other meshes should look pretty smooth though. The deformation transfer implementation is allowed to be a bit slower, probably around 2 fps for the bumpy_plane.

**Comment by gilleswaeber** [comment]
Thank you for your help. I was finally able to fix the problem by moving the call to solve to the callback_pre_draw function.

**Comment by duchaoyu** [comment]
Hi @gilleswaeber, I have the same issue. What do you mean "by moving the call to solve to the callback_pre_draw function."? Thanks in advance for your answer!

**Comment by gilleswaeber** [comment]
That would be
- in the mouse move callback, set a flag instead of computing the new mesh
- in the pre draw callback, check the flag. If set, compute the new mesh and reset the flag

**Comment by juliand665** [comment]
It's pretty late for this, but I figured I'd add that I found the same results as you (computations completing in <50ms despite incredibly stutter-y view)—I got a hunch when I noticed that the time it took to update the view varied so drastically. Indeed setting a flag and solving in the pre-draw hook instead made it work perfectly for me too. I then went to this issue tracker to see if someone else had run into the same problem and found this thread.

@Instructors, I think it would make a lot of sense to update the template with this (for future years), and maybe take it into account too if the issue shows up in people's demos.

**Comment by FloorVerhoeven** [comment]
@juliand665 @resema @duchaoyu What operating system is each of you on?

**Comment by resema** [comment]
MacOS

**Comment by juliand665** [comment]
I'm also on macOS (11.3.1), and I think my mouse is set to a polling rate of 1000 Hz, which would be a pretty absurd speed to try and deform at.

**Comment by duchaoyu** [comment]
@FloorVerhoeven Hi, I'm using windows and my problem is solved...
