### ISSUE TITLE
Error while executing "pull base master" from the tutorial

### ISSUE THREAD

**Issue by popavel** [eth-igl/GP2021-Assignments#9]
While executing the following lines from "Cloning the Assignment Repository" part

cd gp21-'Your_Git_Username'
git remote add base https://github.com/eth-igl/GP2021-Assignments.git
git pull base master

I get the following git error message:

$ git pull base master
remote: Enumerating objects: 1572, done.
remote: Counting objects: 100% (1572/1572), done.
remote: Compressing objects: 100% (1190/1190), done.
remote: Total 1572 (delta 397), reused 1532 (delta 373), pack-reused 0
Receiving objects: 100% (1572/1572), 4.00 MiB | 7.74 MiB/s, done.
Resolving deltas: 100% (397/397), done.
From https://github.com/eth-igl/GP2021-Assignments
 * branch            master     -> FETCH_HEAD
 * [new branch]      master     -> base/master
fatal: refusing to merge unrelated histories

Is it expected to be so?

**Comment by wsh312** [comment]
hi, have you tried: "git pull base master --allow-unrelated-histories"?

**Comment by popavel** [comment]
That helped. Thanks a lot!
