### ISSUE TITLE
Performance/FPS

### ISSUE THREAD

**Issue by Frankie8472** [eth-igl/GP2021-Assignments#90]
"if your implementation does not achieve interactive frame-rates (10+ fps) on all provided meshes it will not receive the full score." 

I am not sure if I did something wrong. I have less than 10 fps on bigger meshes (between 5 and 10, I think). The cores are always on 100% while dragging and I implemented the conditional precomputation (only if a new handle is selected). My laptop, where I run Linux and therefore the assignment, is not very powerful. Even firefox laggs with only one tab open (and only firefox running). So I am not sure if my laptop is the problem or the code. 

Would it be possible to test my code on a machine you know the correct code should achieve 10 fps?

**Comment by FloorVerhoeven** [comment]
Hi @Frankie8472 
From a quick glance at your code it looks like you're doing the right thing with precomputation.
It's okay for the bumpy_plane mesh to be slower, around 2-3fps is what I'd expect there. The other meshes should feel pretty interactive (for example also the camel). The deformation transfer version is also okay to be a bit slower than the standard detail preservation.

We're aware people are on different setups (and Zoom can throttle further) so if the demo looks too choppy we'll double check if something is wrong with your code before deducting points for this.

**Comment by Frankie8472** [comment]
great, thx!!!

**Comment by juliand665** [comment]
I'll add that it's possible you're running into the same issues as #82—there's a [possible fix](https://github.com/eth-igl/GP2021-Assignments/issues/82#issuecomment-843532250) in that thread that greatly improves things on my machine.
