### ISSUE TITLE
Assignment 5: Paper Questions

### ISSUE THREAD

**Issue by Frankie8472** [eth-igl/GP2021-Assignments#91]
After reading the paper 5 times I still feel supid... I hope it's not too late to ask :)

1. Am I correct in my assumption to calculate each Sj in a loop and then solving a linear system (precomputed on G^T*D*G): 
        p'_i = solver.solve(G^T*D*S_i^T) ? Where G^T*D*G is the cotangent matrix of V and F?
2. What shape does the triangle variable t_i have? The formula q → Sj q+tj confuses me.
3. What exactly is p/p_i and how does it look like? (a piecewise linear coordinate function, but I kinda cannot fathom that)

I really have no idea how and what to implement apart from Sj... The paper sounds really interesting and it would kinda be sad if I just gave up and put it away without really understanding it. 

If its too much to ask (like you don't want too hand out too much information), you can ping me that you will answer after the handin (would be ok for me too).

**Comment by FloorVerhoeven** [comment]
Hi @Frankie8472 

1) Calculating each Sj in a loop is right, but then you can assemble all of them together and solve for all p' in 1 go (see Eq. 14). You indeed want to precompute on G^TDG, but only on the submatrix corresponding to the free vertices (like for the first part of the assignment). G^TDG should be equivalent to the cotan Laplacian, but to ensure compatibility with the G^TD used in the right hand side of the solver, I'd recommend using libigl's `igl::grad()` and `igl::doublearea()` to construct it yourself. Also don't forget to subtract the _fc part on the right-hand side (like the first part again). 
2) This formula has very unfortunate notation: q → Sjq+**tj** applies an affine transformation to the point q (e.g. a vertex in triangle j). Sj is a linear transformation (e.g. rotation/scale/shear) and **tj** (in bold) is a translation. So the same Sj and **tj** apply to all vertices in triangle j.
3) The **p** and **q** are the vertex coordinate vectors of the original mesh, and **p'** or **q'** are the coordinates in the deformed mesh. In general this paper denotes _column_ vectors with bold face non-capital letters.
