### ISSUE TITLE
Assignment 6: Scaling of meshes

### ISSUE THREAD

**Issue by MartinaKessler** [eth-igl/GP2021-Assignments#92]
I don't really understand how to scale the meshes. Therefore, I have some questions:

1) Do all the scanned meshes have the same scaling? I.e if scan_1 has one edge of length 1 mm and scan_2 also has one edge of length 1 mm, then those edges have the same length in real-life.

2) On slide 10 of the exercise session about assignment 6 it is written:
![image](https://user-images.githubusercontent.com/79902237/119362133-aeeb8700-bcac-11eb-95d7-5655c35ad327.png)
I don't really understand what you mean by this. I understand how to scale the template such that the average distance to the mean landmark is the same for scan and template. If we scale the template, such that the average distance to the mean landmark is the same for scan_1 and the template, then this might not be true for scan_2 and the template, so there would be a different scaling factor for scan_1 and scan_2. But the sentence "If you rescale scan, make sure scale all scans by same factor" seems to contradict what I just wrote. Or should we rescale the template mesh with a different scaling factor for each scan? Could you please explain what is meant in the exercise slides?

**Comment by wsh312** [comment]
> I don't really understand how to scale the meshes. Therefore, I have some questions:
> 
> 1. Do all the scanned meshes have the same scaling? I.e if scan_1 has one edge of length 1 mm and scan_2 also has one edge of length 1 mm, then those edges have the same length in real-life.

We gather these data from different groups of students in previous years, so we are not sure if they have changed the scale of the meshes. Also when they export the data after the scanning, they could accidentally change the scales as well.


> 2. On slide 10 of the exercise session about assignment 6 it is written:
>    ![image](https://user-images.githubusercontent.com/79902237/119362133-aeeb8700-bcac-11eb-95d7-5655c35ad327.png)
>    I don't really understand what you mean by this. I understand how to scale the template such that the average distance to the mean landmark is the same for scan and template. If we scale the template, such that the average distance to the mean landmark is the same for scan_1 and the template, then this might not be true for scan_2 and the template, so there would be a different scaling factor for scan_1 and scan_2. But the sentence "If you rescale scan, make sure scale all scans by same factor" seems to contradict what I just wrote. Or should we rescale the template mesh with a different scaling factor for each scan? Could you please explain what is meant in the exercise slides?

Please ignore these "hints" if you find all of the data you downloaded are already on the same scale and well positioned (e.g, print the diagonal length of the bounding boxes and center points of all meshes).
