### ISSUE TITLE
Assignment 5 Marking

### ISSUE THREAD

**Issue by boduan1** [eth-igl/GP2021-Assignments#94]
I think it is not reasonable to deduct marks on 'New constraints added after deformation', because this is not asked anywhere in the instruction of the assignment.

**Comment by FloorVerhoeven** [comment]
Hi @boduan1 
This requirement comes down to whether or not you precompute the necessary solvers (and possible other extra precomputations) at the right moment in the timeline of the deformation process, namely between when (new) handles are specified and when you solve for the new vertex positions. 
As the assignment is about making an **interactive** mesh deformation system, the requirement that it also works when adding more handles after an initial deformation is very realistic. It's something that an average user would for sure do, and also something that should show up during testing.
