### ISSUE TITLE
Assignment 6: serialize.h troubleshoot

### ISSUE THREAD

**Issue by Frankie8472** [eth-igl/GP2021-Assignments#96]
Dear SMGP Team,

we are using igl::serialize and igl::deserialize in our code. Now, on mac it seems to work perfectly but on my linux not. The tutorial code 601 fails, no file is written, no file can be read. Returns an empty vector. 

Any idea how to debug/fix that? Maybe I am missing a module or a library?

**Comment by Frankie8472** [comment]
seems to be compatibility issue with mac and linux binaries. I can create, read and edit my own but I cannot edit or read the ones created on mac. 

Is there an os specific binary encoding?

**Comment by Frankie8472** [comment]
hex editing failed (import crashed). probably due to some checksum...

**Comment by FloorVerhoeven** [comment]
Hi @Frankie8472 

It seems from [this pull request](https://github.com/libigl/libigl/pull/1233) and [this issue](https://github.com/libigl/libigl/issues/1198) that cross-platform compatibility is a known issue with libigl's serialization functions. You can try adding the demangle.h and update the serialize.h file according the files changed in the pull request. 

Depending on how large your data is and how badly you want to serialize it, you could consider using libigl's XML serialization instead. It would be slower but should be cross-platform.

Finally you could also try an external serialization library, like for example [this one](https://github.com/USCiLab/cereal) (I don't have personal experience with it though, so your mileage may vary).

**Comment by Frankie8472** [comment]
THX!
