### ISSUE TITLE
Assignment 6: Bonus Tasks

### ISSUE THREAD

**Issue by nwicki** [eth-igl/GP2021-Assignments#98]
- How does the grading work with the bonus task?
- Can we achieve 100% of the points without doing the bonus task?
- How much does it count towards the grade?

**Comment by wsh312** [comment]
-How does the grading work with the bonus task?
As this is an open and kind of competition task, the score will be determined by how other groups perform. But we will try to be on the generous side as long as the minimum is done.

-Can we achieve 100% of the points without doing the bonus task?
Yes, you can.

-How much does it count towards the grade?
As in the slides, they contribute 4 on top of 20 points. And these points are global, meaning that one could have 104 points at maximal in total. Nevertheless, we will in the end design some (non-linear) formula to map your points to [0, 6], so it's unclear right now how one would get a 6, but most certainly if you pass 100, you will get a 6 (it could also be that 81 or 99 is the threshold, I don't know at the moment).

**Comment by wsh312** [comment]
comment for the TA next year: unfortunately, the 6 threshold is above 100 this year, the "global bonus points" was a bad idea, we should keep it 20 points and make all tasks mandatory if there will be not exam again
